### ISSUE TITLE
BDC doesn't work ( just bdc the other provides works fine )

### ISSUE THREAD

**Issue by mathiasbrem** [e-sensing/sits#1023]
**Describe the bug**
Error: .source_items_cube.stac_cube: empty cube metadata (could not retrieve cube metadata)
Traceback:

1. sits_cube(source = "BDC", collection = collection, roi = roi, 
 .     bands = c("EVI", "NDVI"), start_date = start_date, end_date = end_date)
2. sits_cube.stac_cube(source = "BDC", collection = collection, 
 .     roi = roi, bands = c("EVI", "NDVI"), start_date = start_date, 
 .     end_date = end_date)
3. .source_cube(source = source, collection = collection, bands = bands, 
 .     tiles = tiles, roi = roi, start_date = start_date, end_date = end_date, 
 .     platform = platform, progress = progress, ...)
4. .source_cube.stac_cube(source = source, collection = collection, 
 .     bands = bands, tiles = tiles, roi = roi, start_date = start_date, 
 .     end_date = end_date, platform = platform, progress = progress, 
 .     ...)
5. .source_items_cube(source = source, items = items, collection = collection, 
 .     progress = progress, ...)
6. .source_items_cube.stac_cube(source = source, items = items, 
 .     collection = collection, progress = progress, ...)
7. .check_that(x = nrow(cube) > 0, local_msg = "could not retrieve cube metadata", 
 .     msg = "empty cube metadata")
8. stop(sprintf(msg, local_msg), call. = FALSE)

**To Reproduce**
# Define a tile from the CBERS-4/4A AWFI collection
cbers_tile <- sits_cube(
  source = "BDC",
  collection = "CBERS-WFI-16D",
  tiles = "005004",
  bands = [c](https://rdrr.io/r/base/c.html)("B13", "B14", "B15", "B16", "CLOUD"),
  start_date = "2021-05-01",
  end_date = "2021-09-01"
)
# Plot one time instance
[plot](https://rdrr.io/r/graphics/plot.default.html)(cbers_tile, red = "B15", green = "B16", blue = "B13", date = "2021-05-09")

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sits/news/news.html first.

**Comment by gilbertocamara** [comment]
Dear @mathiasbrem 

I have tested your script; it works for me. The Brazil Data Cube requires registration (it's free to use). If you still need to do so, please register at the BDC site (https://brazildatacube.dpi.inpe.br/). After registration, you can request a personal access token (https://brazildatacube.dpi.inpe.br/auth-app/profile/token). Then, please include the token as an environment variable, such as: 

Sys.seten("BDC_ACCESS_KEY " =   "your token").

If this does not work, please let me know.

**Comment by rodrigoesborges** [comment]
> After registration, you can request a personal access token (https://brazildatacube.dpi.inpe.br/auth-app/profile/token). Then, please include the token as an environment variable, such as:
> 
> Sys.seten("BDC_ACCESS_KEY " = "your token").

The link is not working, its being redirected to main bdc page (https://data.inpe.br/bdc/en/home-page-2/) . What would be the up to date process to be able to use the api?

**Comment by gilbertocamara** [comment]
Dear @rodrigoesborges, currently the BDC does not require a token. You can use SITS to access all files.
