### ISSUE TITLE
sits_apply(): An error has occurred in a node and a recovery will be attempted at the end of the process

### ISSUE THREAD

**Issue by marlonfs** [e-sensing/sits#1034]
First of all, sorry for any mistakes! I'm newby to R and sits.
I am trying to add indexes to the SENTINEL-2-16D cube from BDC with `sits_apply()`. I expected this to be a regularized cube, but when running the `sits_apply()` I got an error message:
```{r}
An error has occurred in a node and a recovery will be attempted at the end of the process
```
Then, I tried to run it again and then I got the following error message:
```{r}
Error: sits_apply: cube is not regular, please run sits_regularize() first (.cube_is_regular(cube) is not TRUE)
```
I inserted and ran the `sits_regularize()` first, and the message didn't appear at the first index, but the problem persisted.

Code:
```{r}
library(sits)
library(sitsdata)
library(tibble)
```
```{r}
Sys.setenv("BDC_ACCESS_KEY" = "my_key")

sumare <- sits_cube(
    source = "BDC",
    collection = "SENTINEL-2-16D",
    roi = c("lat_min" = -22.826188,
            "lon_min" = -47.17083,
            "lat_max" = -22.959974,
            "lon_max" = -47.40601),
    start_date = "2022-01-01",
    end_date = "2022-07-30",
    multicores = 8,
    progress= TRUE)
```
```{r}
sumare <- sits_regularize(
  cube=sumare,
  period="P16D",
  res=10,
  output_dir="C:/R_paths",
  roi = NULL,
  multicores = 8,
  progress = TRUE
)

print(sumare)
```
**PS: First I tried running the code without this regularization step above.**
```{r}
# Calculate indexes

#PGI
sumare <- sits_apply(
  data = sumare,
  PGI = 100*(B02*(B08-B04)) / (1-(B02+B03+B08)/3),
  output_dir = "C:/R_paths",
  memsize = 32,
  progress = TRUE)

#PMLI
sumare <- sits_apply(
  data = sumare,
  PMLI = (B11 - B04) / (B11 + B04),
  output_dir = "C:/R_paths",
  memsize = 32,
  progress = TRUE)
```
I noticed that the sits appears not to calculate the index when files are already saved in the output folder. Even if I restart R, clear output and run all chunks.
Although I was aware of the error message, I plotted the index, but it has data gaps (white parts).
```{r}
# select "PMLI" and related bands
sumare_pmli <- sits_select(sumare, bands = c("B04", "B11", "PMLI"))
# Plot the PMLI for the first date
plot(sumare_pmli,
  band = "PMLI",
  dates = "2022-01-01",
  palette = "RdYlGn"
)
```
![image](https://github.com/e-sensing/sits/assets/75811738/20c3eeea-3985-4629-929e-4a45795762a4)

**Comment by OldLipe** [comment]
Hi @marlonfs. Thanks for the descriptive issue. 

I'm using SITS version 1.4.2 and I couldn't reproduce your error. I ran the code below and didn't get the regularization error. Everything was executed correctly, without regularization, since the BDC cubes are already regular.

```R
sumare <- sits_cube(
    source = "BDC",
    collection = "SENTINEL-2-16D",
    roi = c("lat_min" = -22.826188,
            "lon_min" = -47.17083,
            "lat_max" = -22.959974,
            "lon_max" = -47.40601),
    start_date = "2022-01-01",
    end_date = "2022-07-30",
    progress= TRUE
)

# Calculate indexes

#PGI
sumare <- sits_apply(
    data = sumare,
    PGI = 100*(B02*(B08-B04)) / (1-(B02+B03+B08)/3),
    output_dir = "~/tmp/",
    memsize = 32,
    progress = TRUE
)
```

My guess is that the execution of the `sits_apply()` function was interrupted at some point and some dates were missing. That's why the irregularity error in the cube. 

We can check this using the `sits_timeline(sumare)` function, if there are two different timelines this is the case I mentioned above.

The gaps you mentioned in the PMLI index plot are clouds. The `sits_apply()` function uses the CLOUD band to remove the pixels that are marked as clouds, cloud shadow and cirrus. If you want to keep the cloud values, just remove the CLOUD band from the cube. See the plot below: 

![image](https://github.com/e-sensing/sits/assets/28878922/1e377daf-e7fa-4ef2-b39b-5b279340b34c)

**Comment by marlonfs** [comment]
Hi @OldLipe, thanks for replying.

I was using sits version 1.4.1. I updated my version.

I really thought it was a cloud mask, but in the plotting part of the code, the image didn't change when I changed the `dates` parameter, reinforcing the error feeling. Since I was running it locally, now I opened different dates on QGis, and there it seems ok.

It is running again in the updated version, but the process takes a while. I'll let you know the results.

**Comment by marlonfs** [comment]
@OldLipe I got a different error, only in the last index calculus. I'm adding more indexes than the example I gave here, 6 in total.
This time, the process went well until almost the end of the last index. Error message:
```{r}
100%Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `.check_remote_errors()`:
! 7 nodes produced errors; first error: ℹ In index: 2.
Caused by error:
! [readValues] cannot read values
Backtrace:
  1. sits::sits_apply(...)
  2. sits:::sits_apply.raster_cube(...)
  3. sits:::.jobs_map_parallel_dfr(...)
  4. sits:::.jobs_map_parallel(jobs, fn, ..., progress = progress)
  6. purrr::map(...)
     ...
 11. sits (local) .f(.x[[i]], ...)
 12. sits:::.parallel_map(round, fn, ..., progress = progress)
 13. sits:::.parallel_cluster_apply(x, fn, ..., pb = pb)
 14. parallel (local) .check_remote_errors(val)
 15. base::stop(...)
 ```
When I re-ran, this time, instead of showing an error message that the cube was not regular, warning messages appeared about the band already existing on the cube for the first 5 indices, and the last one was calculated normally. Then I added `sits_bands(sumare)` and `sits_timeline(sumare)` and everything looks fine.

In `plot(sumare_pmli, band = "PMLI", dates = "2022-07-28", palette = "RdYlGn")`, the dates parameter still not changing the output, but I checked in QGIS and outputs are ok. 

I think it is important for you to be aware of these minor errors, but for me the question is closed.
