### ISSUE TITLE
Remove purrr::map_dfc, purrr::map_dfr and similar calls

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#1039]
**Describe the requested improvement**
According to the new purrr 1.0.0, these calls have been superseded. The help says:

"The functions were superseded in purrr 1.0.0 because their names suggest they work like ⁠_lgl()⁠, ⁠_int()⁠, etc which require length 1 outputs, but actually they return results of any size because the results are combined without any size checks. Additionally, they use dplyr::bind_rows() and dplyr::bind_cols() which require dplyr to be installed and have confusing semantics with edge cases. Superseded functions will not go away, but will only receive critical bug fixes.

Instead, we recommend using map(), map2(), etc with purrr::list_rbind() and purrr::list_cbind().

**Comment by OldLipe** [comment]
Implement `.map_dfr()` and `.map_dfc()` internal functions.
