### ISSUE TITLE
sits_label_classification : object 'clean' not found

### ISSUE THREAD

**Issue by LorisDeBiasi** [e-sensing/sits#1043]
I'm getting `Error in .check_lgl_parameter(clean) : object 'clean' not found Calls: sits_label_classification ... .check_lgl_parameter -> .check_lgl -> .check_null -> .check_that` when running sits_label_classification (latest sits@dev)

removing the following in `sits_label_classification.probs_cube` fixed it (`clean` and `window_size` removed in 6b055c1301baeb3c1560808ff13766b2748b6cbf)
```
.check_lgl_parameter(clean)
.check_window_size(window_size = window_size, min = 3, max = 15)
overlap <- ceiling(window_size / 2) - 1 # not used
```

**Comment by OldLipe** [comment]
Hi @LorisDeBiasi. Thanks for reporting the bug. I've just fixed it!

The error occurred when exporting the `clean` functionality out of the `sits_label_classification()` function.
