### ISSUE TITLE
error in classification

### ISSUE THREAD

**Issue by lusimac** [e-sensing/sits#1052]
Dear colleagues

I'm trying to classify a modis tile (using deeplearning models) and it presents this error that starts with information about problems with the node during the process..

|=                                                                     |   1%An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process
  |=                                                                     |   2%An error has occurred in a node and a recovery will be attempted at the end of the process

and when it reaches 100% it presents this error as an attachment.

100%Error in `purrr::map()`: In index: 1. Caused by error in `.check_remote_errors()`: ! 69 nodes produced errors; first error:   In index: 1. Caused by error: ! [readValues] cannot read values Backtrace:

the script used is following
cubo <- readRDS("~/Lucrencio/2020/cubos/cubo_classif_012010.rds")

#sits_timeline(cubo)
temp_cnn_model <- readRDS  ("~/Lucrencio/2020/modelos/tempCNN/modis_temp_cnn_012010.rds")
cube_dir <- ("~/Lucrencio/2020/cubos/")
results_dir <- ("~/Lucrencio/2020/resultados/")

sits_timeline(cubo)

##Probabilidade das classes

probs = sits_classify(
  cubo,
  ml_model = temp_cnn_model,
  memsize = 150,
  multicores = 30,
  output_dir = "~/Lucrencio/2020/resultados/probs/",
  version = "v1",
  progress = TRUE,
  verbose = TRUE
)

plot(probs)

![Captura de tela 2023-10-26 085617](https://github.com/e-sensing/sits/assets/89464687/43692e50-e20e-46ed-b546-595cb148df41)

**Comment by OldLipe** [comment]
Hi @lusimac, Thank you for reporting the error. Could you share with us the training samples and the model used so that we can try to reproduce your error?

**Comment by lusimac** [comment]
Hi, Thank you for your reply and sorry for the late reaction... my colleagues informed me that they had the same problem... please find the requested data attached. The model used was tempCNN, Tile 012010 from MOD13Q1-6 data.

Any substantial questions, I am at your disposal. 

Best regards

[amostras_2.csv](https://github.com/e-sensing/sits/files/14195275/amostras_2.csv)

**Comment by OldLipe** [comment]
Error in provider side already fixed.
