### ISSUE TITLE
Image time series analysis using SITS.

### ISSUE THREAD

**Issue by sbht** [e-sensing/sits#1053]
Hello, I am trying to build time series analysis using SITS.  For this, I want to use XGBoost model, one of them ML algorithms. 

I would like to explain detail about my data. I have **13 parameters** (precipitation, humudity, lst, sst, et all.) and I named them **P1**, **P2**, **P3**, **P4**,....,**P13**. The name of the 1st parameter called P1 is precipitation. At the end of the study, **I want to predict the P1 using 12 parameters other than P1**. (I thought I could use the 'sits_xgboost' function for this prediction.)  Each satellite images are the monthly averages of January, February, March, April, May and June of 2003. So there are 6 satellite images for P1, 6 satellite images for P2 and 6 separate satellite images for each parameter.  Totally there are 78 satellite images as single band raster data. The data all fit the definition of '**regular data**'.  

I'm new to SITS but I've created sits_cube and time series table before. I know a little about this. However, **I don't know what kind of XGBoost model I should set up to predict the P1 parameter using sits package**. Now what kind of cube should I create or how should I create a time series table?

**Note:** Additionally, I would like to point out that most of my data is MODIS data. However, there are also different satellite images, such as AIRS.  I named the file names of these satellite images as "MODIS_LOCAL_P1_2003-01-01". And than, I create a sits cube from all my data using sits_cube(). Maybe this is not the right way to create sits_cube. So I know, my data is not from BDC. But it worked. Finallly, I create a time series table from the this raster cube using sits_select function.

Please let me know if you need any further information,
Thank you in advance!
Best regards,
Sebahat.

**Comment by gilbertocamara** [comment]
Dear @sbht, the current version of `sits` is focused on classification, and does not yet support prediction. We are working to include prediction in `sits` version 1.5.0, due to be released in January 2024. Meanwhile, we would appreciate if you could provide the script that you have been using, so we can use it for testing `sits` to support prediction.
