### ISSUE TITLE
sits_get_data()

### ISSUE THREAD

**Issue by AndreSTavares** [e-sensing/sits#1062]
**bug**

Hello, the error occurs in sits version 1.4.2-1

Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented = oriented,  : 
  Loop 0 is not valid: Edge 0 is degenerate (duplicate vertex)

**Script**

library(devtools)
library(sits)

shp_file <- file("~/shape/amostras.shp")
cube <- readRDS(file = "~/cubos/cubo_2020_MODIS_terra.rds")

serie_temporal <- sits_get_data(
  cube = cube,
  samples = "~/shape/amostras.shp",
  shp_attr = "label",
  multicores = 32,
  progress = TRUE)

**Comment by OldLipe** [comment]
Already solved in dev branch. Thanks!
