### ISSUE TITLE
sits_coverage is ignoring some arguments

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#109]
`sits_coverage`, when used with some service, is ignoring some arguments. One possible action is to compare the passed (and currently ignored) argument to the available information about the service and use if it is allowed (a subset of the available values, a value within the available ranges, etc.), or stop with an error otherwise. Current output:

```R
coverage_wtss <- 
    sits_coverage(service = "WTSS-INPE",
                  name    = "MOD13Q1",
                  bands = c("ndvi", "evi"))

coverage_wtss$bands # [1] "mir"  "blue" "nir"  "red"  "evi"  "ndvi"

coverage_wtss <- 
    sits_coverage(service = "WTSS-INPE",
                  name    = "MOD13Q1",
                  bands = c("ndvi", "eviee"))

coverage_wtss$bands # [1] "mir"  "blue" "nir"  "red"  "evi"  "ndvi"
```

**Comment by gilbertocamara** [comment]
Problem solved by Rolf
