### ISSUE TITLE
Incorporar la extracción de puntos con muestreo regular y alteatorio en la funcion sits_get_data

### ISSUE THREAD

**Issue by albertojopia** [e-sensing/sits#1101]
**Describe the requested improvement**
Mejorar la extracción de puntos en la función _sits_get_data_

La función _sits_get_data_ permite realizar un muestreo espacial  de puntos dentro de los polígonos definidos con las clases de uso de suelo. Esta extracción sólo permite realizar un muestreo aleatorio de puntos dentro del polígono, lo cuál algunas veces no representa la variabilidad espacial dentro del polígono. El muestreo regular o sistemático puede mejorar la representación espacial del polígono.

**Associated sits API function**
La función _st_sample_ del paquete _"sf"_ mediante el parámetro _"type"_ permite seleccionar un muestreo espacial _random_, _regular_ u otro método.  Mas información se puede consultar en https://r-spatial.github.io/sf/reference/st_sample.html

La implementación del parámetro _type_ para seleccionar un muestro _regular_ o _random_ en la función  _sits_get_data()_ ayudaría a definir un muestreo acorde a la variabilidad espacial de los polígonos utilizados.

**Comment by gilbertocamara** [comment]
@albertojopia Gracias por la sugestion. La funcion `sits_get_data()` en la version 1.5.0 inclue um nuevo parametro
```{r}
#' @param sampling_type   Spatial sampling type: random, hexagonal,
#'                        regular, or Fibonacci.
```
