### ISSUE TITLE
Convert from 'httr' package to 'httr2' package

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#1103]
According to Hadley: 

"httr2 (pronounced hitter2) is a ground-up rewrite of [httr](https://httr.r-lib.org/) that provides a pipeable API with an explicit request object that solves more problems felt by packages that wrap APIs (e.g. built-in rate-limiting, retries, OAuth, secure secrets, and more)."

**Associated sits API function**
`api_cube`, `api_gdalcubes`, `api_download`and  `api_source_mpc`.

**Comment by OldLipe** [comment]
Create an API of functions that requests services and use the `httr2` as cliente. Like our `raster` API.
