### ISSUE TITLE
RAM issue running dual chanel sits_apply() or sits_get_data()

### ISSUE THREAD

**Issue by marlonfs** [e-sensing/sits#1105]
**Describe the requested improvement**
There is some parallel processing issue when running sits_apply() and sits_get_data() in a computer with 2 or more sticks of RAM. The process runs faster with only one stick. The action is distributed in the number of processes you specify, but they don't run in parallel and take too long time when running in a PC with two RAMs. If you try to run the same code with just one RAM it goes faster.

**Associated sits API function**
sits_apply() and sits_get_data().

**Additional context**
We tested with sticks of 8GB, and it took too long with two RAM. The process was faster with one RAM, but it crashed due to memory overload when it was around 80% progress.

**Comment by gilbertocamara** [comment]
Hi, @marlonfs Could you please provide the script which produced the error so we can try to reproduce it?
