### ISSUE TITLE
netrc access

### ISSUE THREAD

**Issue by reblekah** [e-sensing/sits#1128]
I am getting the following error when trying to access the HLS Data through the sits_cube() function: 

_Error in .source_configure_access.hls_cube(source, collection) : 
  Missing HLS access configuration. Please see instructions in Chapter 4 of on-line book_

I have created multiple .netrc files both in my working directory, and home directory as called by R_user_dir()
All .netrc files are a text file with the machine, login and password calls. 
I'm not sure how to direct sits to where the files are, or if those files are accessed from a specific path specifically but I have tried to store it in the places that seem most logical to me. 
I've also tried using the earthdatalogin package to create and store the files for me and I'm still running into the same error. 
Any suggestions would be appreciated:

**Comment by gilbertocamara** [comment]
Dear @reblekah apologies for the late response. To access NASA HLS, users need to registed at [NASA EarthData](https://urs.earthdata.nasa.gov/), and save their login and password in a ~/.netrc plain text file in Unix (or %HOME%_netrc in Windows). The file must contain the following fields:

machine urs.earthdata.nasa.gov
login <username>
password <password>

The ".netrc" file should be placed in your home directory, and not in your working directory. Please let us know if you can access NASA HLS doing so.

**Comment by gilbertocamara** [comment]
Dear @cboettig Thanks!  We will address this issue and allow alternative ways to configure the `netrc` file, including the use of `earthdatalogin::edl_netrc`.

**Comment by gilbertocamara** [comment]
Dear @reblekah @cboettig, We have now included support for providing the `.netrc' information to access the HLS cloud service. 

We now recommend using the `earthdatalogin` package to create a `.netrc` file with the `earthdatalogin::edl_netrc` function, developed by @cboettig. This function creates a properly configured `.netrc` file in the user's home directory and an environment variable `GDAL_HTTP_NETRC_FILE`. Please take a look at the example below.

```{r}
library(earthdatalogin)

earthdatalogin::edl_netrc( 
username = "<your user name>", 
password = "<your password>" 
) 
```

Then, we check the version of GDAL. In version 3.7.0 or later, we test if the environmental variable `GDAL_HTTP_NETRC_FILE` is present and use it if available to provide the `.netrc` info.  For earlier versions of GDAL, we check the`.netrc` file in the user's home directory. 

For the `.netrc` file, we accept the format used in `sits` 1.5.0, with username and password in different lines, and the one recommended by @cboettig, with all information in a single line. We also accept `.netrc` user files with more than one line, in case they are used to access different services.

We expect to have addressed your issue. Please let us know if you think the matter is solved.
