### ISSUE TITLE
Allow "sf" format for validation data in sits_accuracy() function

### ISSUE THREAD

**Issue by EstefaPizarro** [e-sensing/sits#1150]
**Describe the requested improvement**
One of the arguments of the function sits_accuracy() is "validation", which are the samples to validate the classification.
According with the documentation "The validation data needs to contain the following columns: "latitude", "longitude", "start_date", "end_date", and "label". It can be either a path to a CSV file, a sits tibble or a data frame"; please allow this argument to be in "sf" format and contain the same columns

**Comment by gilbertocamara** [comment]
Dear @EstefaPizarro You can now use both `sf` objects or POINT shapefiles as validation data.
