### ISSUE TITLE
Standardize the use of ROI in data cube regularization

### ISSUE THREAD

**Issue by EstefaPizarro** [e-sensing/sits#1151]
**Describe the requested improvement**
When regularizing a data cube for a bounded region, smaller than a full tile, different satellites handle geometry cropping differently. While Sentinel-2 generates a regular crop by taking the maximum dimensions of the vector file, Sentinel-1 and COP-DEM mask the geometry. This generates disagreements in a possible subsequent treatment of a "merge" cube, because, although the union of the different cubes generated is allowed, the bands that make up it do not have the same dimensions of rows and columns. For example, it is not allowed as input for the segmentation process.

**Comment by OldLipe** [comment]
Create an internal function called `.cube_crop()`  that will be used in `sits_mosaic()` and `sits_regularize()`.
