### ISSUE TITLE
MODIS data cude

### ISSUE THREAD

**Issue by mboumahdi** [e-sensing/sits#1169]
**Describe the requested improvement**
Please provide a concise description of the required improvement. 

Hello, I'm trying to build a data cube of MODIS data snow  index and reflectance but it seems that the package doesn't support MODIS collection MPC. Could you  guide me through this. Thank you

**Comment by gilbertocamara** [comment]
Dear @mboumahdi Access to MODIS product MOD13Q1 collection 6.1 is now available on the development version of `sits` and will be included in version 1.5.1, to be released on July 31st. If you want to use the development version, install it as follows: 
```{r}
devtools::install_github("e-sensing/sits@dev")
```
Do you need other MODIS products from the Planetary Computer? Please tell us and we will make them available in `sits`.

**Comment by mboumahdi** [comment]
Thank you for the answer, I would like to have MOD09GA_006_NDSI  or a daily reflectance at 250 or 500m
Thank you

**Comment by gilbertocamara** [comment]
Dear @mboumahdi are you referring to the MOD09A1 product? Please look at the MPC data catalog.

**Comment by gilbertocamara** [comment]
Dear @mboumahdi I have included the MOD09A1 and MOD10A1 products in the MPC collections that are accessible by `sits`. Please let me know if you need any other collection.

**Comment by mboumahdi** [comment]
Perfect, thanks a lot
