### ISSUE TITLE
confusion in the names of functions

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#118]
Some functions/data of sits do not follow a convention in their names. Usually, sits use only lowercase (even for acronyms - and sits is an acronym written in lowercase) with words separated by underscore:

```
sits_bayes_postprocess()
sits_csv_error_file()
sits_info_services()
sits_ndvi_arima_filter()
point_ndvi
```

However, some functions/data do not follow this convention:

```
sits_TWDTW_classify()
sits_data_toCSV()
.kalmanfilter()
samples_MT_ndvi
sits_shp_toCSV()
```

Shouldn´t they be named as below?

```
sits_TWDTW_classify() -> sits_twdtw_classify()
sits_data_toCSV()     -> sits_data_to_csv()
.kalmanfilter()       -> .kalman_filter()
samples_MT_ndvi       -> samples_mt_ndvi
sits_shp_toCSV()      -> sits_shp_to_csv()
```

**Comment by pedro-andrade-inpe** [comment]
Yes!

**Comment by gilbertocamara** [comment]
I did an initial cleaning of function names today.

**Comment by gilbertocamara** [comment]
Finished cleaning all function names
