### ISSUE TITLE
Generate 1.5.1 release

### ISSUE THREAD

**Issue by luanabeckerdaluz** [e-sensing/sits#1204]
Hi! I noticed that sits 1.5.1 is released on CRAN and current main branch version is also 1.5.1. However, latest Github release is 1.5.0-1.

**Comment by gilbertocamara** [comment]
Dear @luanabeckerdaluz well-spotted! We will do this ASAP!

**Comment by gilbertocamara** [comment]
Dear @luanabeckerdaluz  Release 1.5.1 has been made! Thanks for reminding us!
