### ISSUE TITLE
Download sits_cube data

### ISSUE THREAD

**Issue by hydroversebr** [e-sensing/sits#1206]
Dear,

I hope this message finds you well.

I'm writing to inquire about the possibility of downloading sits._cube data in .tif format. My goal is to subsequently read this data using the spatRast.

Thank you for your time and assistance.

Sincerely,
Arthur.

```

roi_data <- "./dados/pg26_limite_bacia_2009_wgs84.shp"


data <- sits_cube(
  source     = "MPC",
  collection = "COP-DEM-GLO-30",
  bands      = "ELEVATION",
  roi = roi_data
)
```

**Comment by OldLipe** [comment]
Dear @hydroversebr, 

Downloading a cube is carried out using the `sits_cube_copy()` function. The function offers multi-process downloading via the `multicores` parameter.

**Comment by hydroversebr** [comment]
Dear @OldLipe,

Thank you for your previous response.

I've followed your instructions, but I'm still unable to download Copernicus DEM data for the Doce River Basin.

I've used the following code.

Could you please review my code and suggest any potential issues or improvements?

Best wishes,

Arthur.

```
require(devtools)
install_github("hydroversebr/basinPhysiographics")
require(sits)
require(basinPhysiographics)

#create folders
dir.create("./resultados", showWarnings = F)
dir.create("./resultados/demCopSits", showWarnings = F)

#aoi
ae = basinPhysiographics::downloadSubBasinsPNRH(subBasinLevel = 1,
                                                outputDir = "./resultados") %>% 
  dplyr::filter(PS1_NM == "DOCE")


#cube
data <- sits_cube(
  source     = "MPC",
  collection = "COP-DEM-GLO-30",
  bands      = "ELEVATION",
  roi = ae)

#download cube
sits_cube_copy(data,
               n_tries = 5,
               multicores = 18,
               roi = ae,
               output_dir = "./resultados/demCopSits")
```

**Comment by M3nin0** [comment]
Dear @hydroversebr,

Thank you for bringing this issue to our attention and for taking the time to provide a reproducible example.

I was able to run your code and can confirm that the behavior you’re experiencing is not expected. We will investigate this further and work on a fix as soon as possible.

Thanks

**Comment by hydroversebr** [comment]
This project is awesome.

I developed a function to download copernicus DEM. But yours are faster. Soon mine will be deprecated and i will promote yours.

Best wishes.
