### ISSUE TITLE
Fail to download HLS data 

### ISSUE THREAD

**Issue by suffenjoy** [e-sensing/sits#1213]
I tried to download HLS data using sits_cube. I used exactly the same script in https://e-sensing.github.io/sitsbook/earth-observation-data-cubes.html#harmonized-landsat-sentinel, but got an error message of Error: .check_stac_items: NULL value not allowed for items - collection search returned no items check 'roi', 'start_date', 'end_date', and 'tile' parameters. 
The .netrc file is set successfully, and I've downloaded HLS with other package on this desktop before. 

`
# define a region of interest
roi <- c(
  lon_min = -45.6422, lat_min = -24.0335,
  lon_max = -45.0840, lat_max = -23.6178
)

# create a cube from the HLSS30 collection
hls_cube_l8 <- sits_cube(
  source = "HLS",
  collection = "HLSL30",
  roi = roi,
  bands = c("BLUE", "GREEN", "RED", "CLOUD"),
  start_date = as.Date("2020-06-01"),
  end_date = as.Date("2020-09-01"),
  progress = FALSE
)
# merge the Sentinel-2 and Landsat-8 cubes
hls_cube_merged <- sits_merge(hls_cube_s2, hls_cube_l8)
`

**Comment by M3nin0** [comment]
Dear @suffenjoy,

Thank you for your contribution and for providing a reproducible example.

In our tests, we were able to replicate the error you mentioned. In an initial analysis, we identified that the HLS STAC service is currently undergoing updates, leading to changes in some API parameters. We also observed instabilities in the image search.

We will continue monitoring the HLS STAC service and, as soon as it stabilizes, release a hotfix to address the identified issues.

Thank you! 
Felipe Carlos

**Comment by M3nin0** [comment]
Dear @suffenjoy,

We are still following your issue. Other users also reported issues with their service (https://forum.earthdata.nasa.gov/viewtopic.php?t=5922). As soon as we have some news, we'll update you.

Cheers,
Felipe Carlos

**Comment by M3nin0** [comment]
Dear @suffenjoy,

We are still following your issue. As described in the forum, the services are not normalized yet (https://forum.earthdata.nasa.gov/viewtopic.php?t=5922). As soon as we have some news, we'll update you.

Cheers,
Felipe Carlos

**Comment by gilbertocamara** [comment]
Dear @suffenjoy, NASA has improved their STAC service and we have adjusted our code. This problem will be corrected in sits 1.5.2.
