### ISSUE TITLE
sits_mosaic() multicores error

### ISSUE THREAD

**Issue by paulacopelli** [e-sensing/sits#1220]
**Describe the bug**  
I encountered an error when using the `sits_mosaic()` function. Despite the layers being processed 100%, the final step of merging them was not completed. The error only occurs when using multiple cores.

**To Reproduce**  
I ran the following code with 2 cores:

```
mosaic_dem <- sits_mosaic(
  cube       = cube_itata,
  crs        = "EPSG:32718",       # I tried with and without the crs
  roi        = roi_itata,
  multicores = 2,
  output_dir = paste0(raiz,"/out/cube_itata_mosaic"),
  version = "v3"
)
```

I received the following error message:

```
|=========================================================================================| 100% 
Error in purrr::map():
ℹ In index: 1.
Caused by error in .check_remote_errors():
! 1196 nodes produced errors; first error: Write error.
---
Backtrace:
     ▆
  1. ├─sits::sits_mosaic(...)
  2. │ └─sits:::.jobs_map_parallel_dfr(...)
  3. │   └─sits:::.jobs_map_parallel(jobs, fn, ..., progress = progress)
  4. │     ├─base::unlist(...)
  5. │     └─purrr::map(...)
  6. │       └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  7. │         ├─purrr:::with_indexed_errors(...)
  8. │         │ └─base::withCallingHandlers(...)
  9. │         ├─purrr:::call_with_cleanup(...)
 10. │         └─sits (local) .f(.x[[i]], ...)
 11. │           └─sits:::.parallel_map(round, fn, ..., progress = progress)
 12. │             └─sits:::.parallel_cluster_apply(x, fn, ..., pb = pb)
 13. │               └─parallel (local) .check_remote_errors(val)
 14. │                 └─base::stop(...)
 15. └─base::.handleSimpleError(...)
 16.   └─purrr (local) h(simpleError(msg, call))
 17.     └─cli::cli_abort(...)
 18.       └─rlang::abort(...)
```

However, running the same code with 1 core instead allowed the process to proceed:

```
mosaic_dem <- sits_mosaic(
  cube       = cube_itata,
  crs        = "EPSG:32718",
  roi        = roi_itata,
  multicores = 1,
  output_dir = paste0(raiz,"/out/cube_itata_mosaic"),
  version = "v3"
)
```

It skipped the already processed layers and successfully merged the mosaics.  

**If reporting a change from previous versions**  
Version: sits 1.5.1

**Additional context**  
Running the mosaic with 1 core from the beginning also produces an error, but rerunning with 1 core after the initial failure works.

**Comment by OldLipe** [comment]
Dear @paulacopelli ,

Thank you for your contribution and for providing a reproducible example.

We had the same behavior in some experiments that we did. We will investigate and return to you as soon as possible.

Thank you!
Felipe Carvalho

**Comment by OldLipe** [comment]
Related to #1221

**Comment by gilbertocamara** [comment]
Dear @paulacopelli we has solved your problem. The correction is currently in the development version of `sits` and we will load the corrections to CRAN on November 20th. To get the latest version of `sits`, please run the command
```{r}
% devtools::install_github("e-sensing/sits@dev")
```
