### ISSUE TITLE
Error with `sits_get_data`

### ISSUE THREAD

**Issue by paulacopelli** [e-sensing/sits#1223]
Hello!  
I encountered an issue where, despite having a valid data cube for `sits` and a set of points from which I want to extract information, I received an error.

Code:
```
samples_itata <- sits_get_data(
  cube = cube_itata_mosaic,                # data cube to extract information from
  samples = Puntos_totales,                # sample points
  bands = sits_bands(cube_itata_mosaic),   # bands to extract the time series from
  label_attr = "label",                    # attribute column for class label of each sample
  pol_id = "Nivel3",                       # polygon ID
  crs = "EPSG:32718",                      # coordinate reference system
  multicores = 1,                          # number of cores to process the time series
  progress = TRUE                          # show progress bar
)
```

I don't have the exact error message, but it was related to "invalid input," without specifying whether it referred to the data cube or the sample points.

**Comment by gilbertocamara** [comment]
Dear @paulacopelli, this error could be caused by a mismatch between the format of your input data ("puntos totales"). the function `sits_get_data()` accepts samples in different formats. The most common would be CVS files or SHP files. In these cases, the function requires you to provide a valid path (e.g. "/path_to_my_files/puntos_totales.shp" or  "/path_to_my_files/puntos_totales.csv".

An alternative our be to read the SHP files as an `sf` object, for example

```{r}
puntos_totales <- sf::st_read("/path_to_my_files/puntos_totales.shp") 
````
This `sf` object can be used as a `samples` parameter to the `sits_get_data()` function.

Could you share with us your sample file?

**Comment by paulacopelli** [comment]
Dear Gilberto. Thank you very much for your response. Indeed, the file I am using to extract data is a .shp file. I tried the suggestion you provided but it doesn't solve the problem. I just realized that the problem is not the samples or the cube in general, but rather the index files, this is because when I delete the indexes from my data cube, the extraction works fine, so must be something wrong with sits_apply(), wich I described earlier

**Comment by gilbertocamara** [comment]
Dear  @paulacopelli we are working on a more long-lasting solution to your problem. Please see issue #1231

**Comment by gilbertocamara** [comment]
Dear @paulacopelli we has solved your problem. The correction is currently in the development version of `sits` and we will load the corrections to CRAN on November 20th. To get the latest version of `sits`, please run the command
```{r}
% devtools::install_github("e-sensing/sits@dev")
```

**Comment by gilbertocamara** [comment]
Dear @paulacopelli we has solved your problem. The correction is currently in the development version of `sits` and we will load the corrections to CRAN on November 20th. To get the latest version of `sits`, please run the command
```{r}
% devtools::install_github("e-sensing/sits@dev")
```
