### ISSUE TITLE
sits_cube with local data

### ISSUE THREAD

**Issue by safalabolo** [e-sensing/sits#1225]
Hello!

Describe the requested improvement:
I would like to propose an enhancement for the sits_cube function that would make it easier to work with local data sources. Currently, the function allows users to create data cubes from image collections available in various cloud services, as well as from local files. However, the documentation can be confusing, and there might be room for improvements to streamline the process of creating cubes from local datasets.

Specifically, I suggest improving the clarity of the documentation regarding the requirements and parameters for using local data. Additionally, enhancing error messages when files do not conform to expected naming conventions could greatly assist users in troubleshooting.

Associated sits API function:
The function in question is sits_cube. It should work as follows when utilizing local data:

The data_dir parameter should clearly specify the directory where images are stored, and it should handle subdirectories if applicable.
The parse_info parameter should include detailed examples of expected file name structures for various data types (e.g., MODIS, Landsat, Sentinel).
Consider implementing a validation function to check if the local data conforms to the required format before attempting to create the cube.
Additional context:
Currently, users must ensure that all images have the same spatial resolution and projection and that each file contains a single image band for a single date. Providing more explicit guidance on how to format file names (e.g., including examples of valid and invalid names) would enhance user experience.

Incorporating these improvements would make the sits_cube function more accessible to users who primarily work with local data, thus broadening its usability and appeal.

**Comment by gilbertocamara** [comment]
Dear @safalabolo many thanks! we will include your suggestions in the documentation and in the book

**Comment by M3nin0** [comment]
Dear @safalabolo,

Thank you for your suggestion! We've updated our documentation to provide a clearer explanation of how to use local cubes.

To install the latest version, please use the following command:

```
devtools::install_github("e-sensing/sits@dev")
```

We truly appreciate your contribution.

Best regards,
Felipe Carlos

**Comment by safalabolo** [comment]
Dear @gilbertocamara & @M3nin0 ,

Thank you very much for considering my suggestions and for updating the documentation. 

I truly appreciate the effort you’re putting into improving both the documentation and the book.

I’ll proceed with installing the latest version using the provided command. 

Thanks again for your support and responsiveness!

Best regards,
Salvatore
