### ISSUE TITLE
sits_classify with XGBoost doesn't crop the ROI

### ISSUE THREAD

**Issue by EstefaPizarro** [e-sensing/sits#1227]
**Describe the requested improvement**
When applying the X function, using XGBoost as a training model, the tiles are not cropped to the study area provided by the ROI parameter. The tiles are cropped to the study area when this process is performed with a Random Forest model.
For the particular case of the Chilean machine, a test was performed with tiles 19HBA and 19HCA with both models. The result with XGBoost returns the complete tiles, making the process less optimal. On the contrary, the result with Random Forest returns the tiles cut according to the region.

**Associated sits API function**
Please verify the 'roi' parameter of the sits_classify function

**Comment by M3nin0** [comment]
Dear @EstefaPizarro,

Thanks a lot for reporting this issue and for taking the time to provide this detailed description.

We will investigate this issue and return to you as soon as possible.

Cheers,
Felipe Carlos
