### ISSUE TITLE
Improve timeout handling in sits_cube_copy 

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#1231]
**Describe the requested improvement**
Some cloud providers (e.g., MPC) impose a timeout for downloading data from their repositories. This timeout causes problems when using `sits_cube_copy()` to extract medium and large-sized data cubes as local archives. Currently, `sits` obtains a new token on a tile-by-tile basis. This is not enough to guarantee that all images from the tile will be downloaded safely. 

For this reason, we need to change `sits_cube_copy()` to obtain a new token on a band-by-band basis, and then check the integrity of all time instances from each band. After each file is downloaded, we need to run an integrity test. If it fails, the download needs to restart. 

**Associated sits API function**
`sits_cube_copy()`

**Comment by frazucca** [comment]
Hi,
I don't know if help to this  Issue  but after  submitting the following request to **CDSE** 
_s2_16_24MMU_cubeCDSEx <- sits_cube(source = "CDSE", collection = "SENTINEL-2-L2A", tiles = "32SNJ", bands = c("B8A"), start_date = "2016-01-01", end_date = "2024-10-30")_
I get this error msg
**_Error in `httr2::req_perform()`:
! HTTP 504 Gateway Timeout._**

So here the output of rlang::last_trace

_Backtrace:
     ▆
  1. ├─sits::sits_cube(...)
  2. └─sits:::sits_cube.stac_cube(...)
  3.   ├─sits:::.source_cube(...)
  4.   └─sits:::.source_cube.stac_cube(...)
  5.     ├─sits:::.source_items_new(...)
  6.     └─sits:::.source_items_new.cdse_cube(...)
  7.       ├─sits:::.opensearch_cdse_search(...)
  8.       └─sits:::.opensearch_cdse_search.S2MSI2A(...)
  9.         └─sits:::.opensearch_cdse_client(...)
 10.           ├─sits:::.get_request(url = collection_url, query = query)
 11.           └─sits:::.get_request.httr2(url = collection_url, query = query)
 12.             ├─sits:::.request(req_obj, verbosity = quiet, ...)
 13.             └─sits:::.request.httr2(req_obj, verbosity = quiet, ...)
 14.               └─httr2::req_perform(req_obj, ...)
 15.                 └─httr2:::handle_resp(req, resp, error_call = error_call)
 16.                   └─httr2:::resp_abort(resp, req, body, call = error_call)
 17.                     └─rlang::abort(...)_


All the best!!

fz

**Comment by gilbertocamara** [comment]
Dear @frazucca Your problem is likely due to CDSE timeout. Access to CDSE is sometimes very slow, and sometimes you get a timeout because of the inability of CDSE to respond to many queries in parallel. I suggest you try AWS or MPC, which are much faster than CDSE.

**Comment by frazucca** [comment]
dear @gilbertocamara, you're right,  but CDSE contains more images for each tiles, at least for the area of my interest (Sardinia and Corsica).  I'll simplify the query, aka shortly the time span per query.
Thank you for the great effort
ciao
fz
