### ISSUE TITLE
Pixels without a class are mislabeled

### ISSUE THREAD

**Issue by EstefaPizarro** [e-sensing/sits#1234]
When I did the training and classification for the Maule Region (Chile), specifically a mountainous area of ​​the Andes, the final map gives the value 1 (first label of the data set) to the pixels without data (this is from prior knowledge, in the mountain range, with that height above sea level, that coverage does not exist and it is a site of high cloudiness throughout the year)

I share the script with the routes to the inputs to replicate the process
https://gist.github.com/EstefaPizarro/2db3622bd9e2702899c4cd0e8c5e739c

Regards, 
Estefanía

**Comment by gilbertocamara** [comment]
Thanks, @EstefaPizarro! To put your information in context, here's more detail.

In areas with significant cloud coverage, time series data may occasionally be fully obscured. Currently, the `sits` function assigns a value of zero to all instances in these time series to facilitate classification by machine learning (ML) algorithms. However, these algorithms subsequently generate arbitrary probabilities for the pixels, leading to inaccuracies. This error then propagates through the `sits_smooth` and `sits_label_classification()` functions, resulting in a map with incorrectly labeled points. Areas with no data could be assigned to a specific class incorrectly.

To address this issue, we need to modify several functions: `sits_regularize()`, `sits_classify()`, `sits_smooth()`, `sits_label_classification()`, `sits_variances()`, `sits_uncertainty()`, `plot()`, and `sits_view()`. Here are some suggestions for each:

1. **`sits_classify()`**: When reading a block of input data to classify, we should generate a temporary binary block that serves as a "data/nodata" mask. After the ML algorithm produces probabilities for this block, we need to apply the mask to the probability block, setting the pixels marked as nodata to NA.

2. **`sits_smooth()`**: The smoothing function needs modification to exclude NA values from the smoothing process. This adjustment will allow for the replacement of many NA values with valid neighboring probabilities.

3. **`sits_label_classification()`**: This function should recognize NA values and assign them to a NODATA class, which could default to zero.

4. **`sits_uncertainty()`**: This function should identify NA values and refrain from including them in calculations.

5. **`sits_variances()`**: This function should follow the same approach as `sits_uncertainty()`.

6. **`plot()`**: We need to test whether the `tmap` package handles NA values effectively.

7. **`sits_view()`**: Similar to `plot()`, we should verify how this function deals with NA values.

I hope this clarifies the requirements for addressing the issues with the time series data!

**Comment by EstefaPizarro** [comment]
Thanks a lot for your response, @gilbertocamara ; this clarifies the reason for the values obtained. 
I wish you success in improving the process.!

Regards

**Comment by EstefaPizarro** [comment]
In the new development version, the function sits_classify() returns the following error:

maule_probs1 <- sits_classify(
data = cube,
roi = roi_maule,
ml_model = rfor_model1,
output_dir = "/data/out/08.Classify/Pixel/Prueba1/Ajuste/",
version = "v1",
multicores = 12,
memsize = 48)
  |================================================================================================================| 100%
**Error in `purrr::map()`:
ℹ In index: 1.
Caused by error:
! sits_crop: Source and destination directories must be different - Invalid `output_dir` parameter
Run `rlang::last_trace()` to see where the error occurred.**


The file is generated, but this error occurs for each tile that is processed from the cube

**Comment by gilbertocamara** [comment]
Dear @EstefaPizarro thanks. We will work to find the problem.

**Comment by M3nin0** [comment]
Dear @EstefaPizarro,

Thank you very much for bringing this issue to our attention.

I tried to reproduce the new error you described, but I was unable to do so. I used the development version of `sits` along with the scripts you shared (https://gist.github.com/EstefaPizarro/2db3622bd9e2702899c4cd0e8c5e739c).

Could you please share the script you are using? This would help me reproduce the issue

Best regards,
Felipe Carlos

**Comment by M3nin0** [comment]
Dear @EstefaPizarro,

Thank you so much for sharing your code!

I attempted to reproduce the error you mentioned but could not do so. The script you provided ran without any issues on my end.

The only modification I made to your script was to turn off the use of the `pacman` package, as shown below:

```r
# Carga de paquetes y limpieza de ambiente --------------------------
# pacman::p_load("sits", "sitsdata", "sf", "tidyverse", "tmap")
# rm(list = ls())
library(sits)
library(sf)
```

I recommend reinstalling the development version of the `sits` package and trying to rerun your script without relying on `pacman`. This might help resolve any underlying issues.

Please let me know how it goes or if you encounter any further error.

Best regards,
Felipe Carlos

**Comment by EstefaPizarro** [comment]
Dear @M3nin0 , 

Last night I ran a classification and a smoothing and I did not have the error mentioned again, the issue can be considered closed.

Thanks a lot!
Best regards, 

Estefania

**Comment by M3nin0** [comment]
Dear @EstefaPizarro,

Thank you so much for your feedback!

Please don't hesitate to open new issues whenever necessary.

Cheers,
Felipe Carlos
