### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#133]
An error message produced by sits_select_bands wrongly references the sits_select function

``
library(sits)
data(samples_MT_9classes)
bs <- c(sits_bands(samples_MT_9classes), "fake_bands")
sits_select_bands(samples_MT_9classes, bs)

> Error: conditions failed for call 'sits_select_bands(samples_MT_9classes, bs)':
	 * all(bands %in% sits_bands(.))
 Description: sits_select: some band(s) not found in input data 
``

**Comment by rolfsimoes** [comment]
In this case, use the `sits_select_bands_` function.

**Comment by pedro-andrade-inpe** [comment]
The message will be improved to:

```
"sits_select_bands: the following bands do not exist in the input data: fake_bands"
```
