### ISSUE TITLE
Overwrite results

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#138]
The function `sits::sits_classify_raster` overwrites former results and  it doesn't provide a way to control this behavior. This could lead to undesired results, specially when classifying large data sets.

The overwrite parameter is burn in the code at  `sits:::.sits_classify_multicores`

**Comment by gilbertocamara** [comment]
The function sits_classify now has an additional parameter called "version" (by default, its value is "v1"). By changing this parameter, users can control the version of the classified files.
