### ISSUE TITLE
NDVI and EVI default values

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#139]
The default property (config.yml) RASTER_minimum_value for NDVI & EVI is -3000.

The NDVI is defined in the interval [-1, 1]. In remote sensing, it is common practice to use surface reflectance (SF), which are defined in the interval [0, 1]. For storage convenience, the SF values are stored as integers in the interval [0, 10000]. By analogy, the NDVI image would be expected to fall in the interval [-10000, 10000] making the minimum value -10000 instead of -3000. Although, negative NDVI values are rare in Land Use/Cover applications, this change would improve SITS coherence.

Similarly to SF, the EVI is defined in the interval [0, 1]. However, unlike the other default values (which are set to 0), the EVI minimum is -3000.

As said before, these small changes could increase the SITS coherence and could extend its use beyond LUC applications.

**Comment by gilbertocamara** [comment]
The minimum values of NDVI and EVI are set based on the MODIS defaults.
