### ISSUE TITLE
Support Nearby Crop

### ISSUE THREAD

**Issue by harryprince** [e-sensing/sits#144]
Hi e-sensing team,
      I am using Keras and satellites image to train a GAN model with resnet50 pretrained model(224x224x3). In the training process, the nearby crop with `st_geohash`  plays a critical role as a data loader.
     Does anyone can give me a suggestion to do that in `sits` package, or I am willing to contribute my solution too.

**Comment by rolfsimoes** [comment]
Hi @harryprince, the `sits` package uses Keras to classify satellite image time series. It looks for the time dimension to load the data used during the training process. The classification is done pixel by pixel. You can see how `sits` uses Keras by looking at the function `sits_deeplearning` in `R/sits_machine_learning.R` file.
