### ISSUE TITLE
sits_classify does not run on Windows

### ISSUE THREAD

**Issue by oldi** [e-sensing/sits#149]
I tried to run the _classify_deeplearning_ demo as well as the much simpler _classify_csv_ demo, and in both cases the warning was:

> Starting classification at 2019-08-06 10:24:00
Error in parallel::mclapply(chunk.lst, scale_block, scale_factor, mc.cores = multicores) : 
  'mc.cores' > 1 is not supported on Windows

I tried to set mc.cores to zero or to 1 but it did not run. Is there any way to run the function without multiple cores or to use SOCK instead?

**Comment by gilbertocamara** [comment]
Dear Jens

Good point!! We will try to solve this ASAP. Our working environments are Linux and MacOS. 

Best
Gilberto

**Comment by gilbertocamara** [comment]
Dear oldi, this issue should be fixed in SITS version 0.9.2 Please let us know if you still have problems.

**Comment by oldi** [comment]
Dear Gilberto,
sorry for the late response. Now it works perfectly well.
Thank you very much!
