### ISSUE TITLE
bad error when using more neurons than samples

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#151]
In `sits_cluster_som()`, when there are more neurons than samples in the input data, it stops with a strange error. The code below reproduces the problem:
```R
require(sits)
data("samples_mt_6bands")
data.tb <- samples_mt_6bands
som_cluster.tb <-
    sits::sits_cluster_som(
        data.tb,
        grid_xdim = 50,
        grid_ydim = 20,
        rlen = 100,
        distance = "euclidean",
        mode = "pbatch",
        iterations = 2

    )
```

The code above shows the following error:

```
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'
```

Think in a better error message.

**Comment by gilbertocamara** [comment]
Problem fixed in version 0.9.2. Note that the API of the sits_cluster_som function has been simplified, and parameters "rlen", "distance" and "mode" are no longer used.
