### ISSUE TITLE
package ‘wtss’ is not available (for R version 4.0.0) 

### ISSUE THREAD

**Issue by hakimabdi** [e-sensing/sits#164]
The installation results in the error below:
```
Error: Failed to install 'sits' from GitHub:
  (converted from warning) package ‘wtss’ is not available (for R version 4.0.0) 
```

**Comment by pedro-andrade-inpe** [comment]
Dear @hakimabdi, package WTSS was temporally removed from CRAN. You need to install it from GitHub directly.

```R
devtools::install_github("e-sensing/WTSS")
```

We have just updated the source code (https://github.com/e-sensing/sits/pull/163).
