### ISSUE TITLE
sits_cube_copy error

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#178]
sits_cube_copy throws an error while making a local copy of an AWS cube and  the cube has more then one tile.

I traced the error back to line 635 in sits_cube.R:

dest_file <- paste0(dest_dir,"/", cube$satellite,"_", cube$sensor, "_",
row$band, "_", row$date, ".", file_ext)

When the cube object has more than one tile (e.g. two rows in its internal tibble), the variable dest_file is a character of lenght two, which is feed into a call to gdalUtils::gdal_translate, which cannot handle more than one destination file.

**Comment by gilbertocamara** [comment]
Alber, thanks for pointing out. The issue has been corrected in the new version.
