### ISSUE TITLE
Error in .sits_raster_block_list

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#225]
The function `.sits_raster_block_list` returns a list where its last element is NA for `row ` and `nrows`. This makes sits to try to create a sub_image of unknown size, causing an error during classification.

`library(sits)`
`my_sub_image <- c(nrows = 7324, ncols = 11204, first_row = 1, first_col = 1)`
`for (i in 385:389) {`
`    print(sprintf("Last element when i == %s", i))`
`    sits:::.sits_raster_block_list(nblocks = i,`
`                            sub_image = my_sub_image) %>%`
`        dplyr::last() %>%`
`        print()`
`}`

**Comment by gilbertocamara** [comment]
Alber, thanks for flagging the problem; Rolf and me have corrected the error.
