### ISSUE TITLE
Como criar um cubo de dados para landasat-8 

### ISSUE THREAD

**Issue by HugoFukuzava** [e-sensing/sits#227]
Olá, tentei criar um cubo landsat de dados a partir de séries temporais (evi_approx (1).TIFF, ndwi_approx (1).TIFF, ndvi_approx (1).TIFF) no qual tenho a timeline.txt.

```
`ndvi_file <- ("D:/Hugo/Projetos_Pesquisa/Sits_cana/Novas_1409/ndvi_approx (1).tif")
evi_file <-  ("D:/Hugo/Projetos_Pesquisa/Sits_cana/Novas_1409/evi_approx (1).tif")
ndwi_file <- ("D:/Hugo/Projetos_Pesquisa/Sits_cana/Novas_1409/ndwi_approx (1).tif") 

data_dir <- c(ndvi_file, evi_file, ndwi_file)
band <- c("ndvi", "evi", "ndwi")

#time_file <- "D:/Ana/Projetos_Pesquisa/Sits_cana/timeline2.txt"
#timeline <- scan(time_file, character())

```
cube <- sits_cube(
  source = "LOCAL",
  name = "022024",
  satellite = "LANDSAT-8",
  sensor = "OLI",
  data_dir = data_dir,
  delim = "_",
  parse_info = c("X1", "X2", "band", "date")
)`
```
```
                  
                  **Error: Can't subset columns that don't exist.
x Column `date` doesn't exist.**

**Comment by OldLipe** [comment]
Olá Hugo. Tudo bem?

No parâmetro ```data_dir``` é esperado o diretório de suas imagens, logo, no seu exemplo seria: ```D:/Hugo/Projetos_Pesquisa/Sits_cana/Novas_1409/```. 

Refiz o seu exemplo e vou listar aqui alguns detalhes que podem te auxiliar:

- No nome do arquivo não é especificado a data da imagem. Uma forma de adicionar a data seria ```ndvi_2019-01-01_approx (1).tif```.
- Com a adição da data no nome do arquivo, o seu ```parse_info``` ficaria assim: ```parse_info = c("band", "date", "X1")```
- Outro detalhe é o índice ```ndwi``` que não é especificado no **sits**. Com isso, é necessário especificar os detalhes desse índice no arquivo de configuração do usuário, criei um gist para exemplificar o seu caso: [gist](https://gist.github.com/OldLipe/ad3228b2ec9fc0fedf28a9cf6dd7f26e . Veja que, os valores de mínimos, máximos, ausentes e escalas devem ser alterados conforme os valores de suas imagens. 
- Após criar esse arquivo com extensão ```.yml``` em seu computador, é necessário criar uma variável de ambiente que "mostre" para o sits onde ele pode ser encontrado, para isso, pode ser uitilizado o comando ```Sys.setenv()```.

No trecho de código abaixo, coloquei um exemplo de como pode ser criado esse cubo com base nas observações que postei anteriormente: 
 
```r
#
# carregando o pacote sits
#
library(sits)

#
# adicionando o arquivo de configuracao na variavel de ambiente "SITS_USER_CONFIG_FILE"
#
Sys.setenv("SITS_USER_CONFIG_FILE" = "D:/dir/config/config_example.yml")

#
# diretorio em que se encontram as imagens, obs: nome da imagem que usei: "ndvi_2019-01-01_approx (1).tif"
#
data_dir <- "D:/Hugo/Projetos_Pesquisa/Sits_cana/Novas_1409"

#
# criacao de um cubo local
#
cube <- sits_cube(
    source = "LOCAL",
    name = "022024",
    satellite = "LANDSAT-8",
    sensor = "OLI",
    data_dir = data_dir,
    delim = "_",
    parse_info = c("band", "date", "X1")
)
```

Qualquer dúvida, estou à disposição.

**Comment by rolfsimoes** [comment]
Olá @HugoFukuzava, tudo bem?

Complementando a resposta do @OldLipe, parece que o exemplo colocado é da versão anterior do sits (0.10.0).
Na atual versão (0.11.0), o sits não suporta mais arquivos do tipo "brick", que parece ser o seu caso.

Então para conseguir processar o seu experimento, vc deverá usar os arquivos que deram origem ao seus bricks. O sits é capaz de ler, reconhecer, remover nuvens, interpolar os dados e processar a classificação de séries temporais.

Para isso, como o @OldLipe comentou, vc precisa fornecer o diretório dos arquivos `.tif` das imagens separadas por banda e data. Esses arquivos precisam estar na mesma pasta e indicarem no nome do arquivo, em alguma posição do nome, a banda e a data. Por exemplo, suponha que o diretório dos arquivos seja `"C:/Meus arquivos/Landsat-8/"` e os arquivos tenham o seguinte formato de nome: `LC08_L1TP_157072_20210329_20210329_01_T1_B3.TIF`. Usando o delimitador `"_"` para separar as partes do nome do arquivo, teríamos: 1) `LC08` 2) `L1TP` 3) `157072` 4) `20210329` 5) `20210329` 6) `01` 7) `T1` 8) `B3`. O que o sits precisa saber é do 4) e do 8), assim o parâmetro `parse_info` da função `sits_cube` deveria ser para o exemplo `c("", "", "", "date", "", "", "", "band")`.

O segundo passo é colocar as informações da banda conforme o @OldLipe explicou. Isso deve resolver o problema.

**Comment by HugoFukuzava** [comment]
Olá muito obrigado consegui criar com sucesso o cubo, porém na nomenclatura do file.tif tive que alterar o NDVI "**ndvi**_2019-01-01_approx (1).tif" por "**B1**_2019-01-01_approx (1).tif" pois ele não reconheceu o "ndvi".

Outra duvida, dentro dos arquivos TIF possuo **108 bandas** em diferentes datas, será existe uma forma melhor de se criar o cubo sem eu ter que extrair banda por banda e renomear por "ndvi_**2019**-01-01_approx (1).tif , ndvi_**2018**-01-01_approx (1).tif".

Desculpe caso a questão fique muito solta.

Att. Hugo

**Comment by OldLipe** [comment]
Olá @HugoFukuzava . Tudo bem?

Que bom que conseguiu!

Em relação a sua primeira questão, nós acabamos de corrigir esse bug, veja em #239 .

Sobre o uso de arquivos tif com diversas imagens (o que chamamos de brick), não é mais suportado pelo sits. O brick foi substituído por arquivos independentes (o qual chamamos de stack). Desta forma, é necessário "explodir" os seus bricks em vários arquivos. Para te auxiliar criamos uma função: https://gist.github.com/OldLipe/b2c0a66e1cf3c742892e504b3512313f

OBS.: Note que a função deverá ser usada para cada brick em sua máquina. As imagens serão salvas em uma pasta chamada "stack", que será localizada na pasta dos seus bricks. 

Atenciosamente, Felipe.
