### ISSUE TITLE
sits 1.0.0 in CRAN

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#243]
We expected to solve a number of open issues to be able to produce a 1.0.0 version of SITS to be loaded into CRAN. These issues include:

(a) Support for LANDSAT-8 using the USGS STAC
(b) Support for MS Azure Cloud
(c) Revision of sits documentation 
(d) Support of data cubes coming from ARD collections having tiles with different timelines.

**Comment by OldLipe** [comment]
Hi Gilberto. We can use the package function `usethis::use_release_issue` to map our roadmap to send to CRAN.
