### ISSUE TITLE
Support of data cubes coming from ARD collections having tiles with different timelines.

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#245]
Include functions that support data cubes from ARD collections that have different timelines for their tiles. 

The "interp_fn" function is used when the training samples which were used to generate the classification model have a larger number of time instances than the data cube. In this case, pixel time series  of the data cube will have to be interpolated to fit that of the samples.

The "compose_fn" function is used when the training samples which were used to generate the classification model have a small number of time instances than the data cube. In this case, pixel time series of the data cube will have to be composed and/or merged to fit that of the samples.

**Comment by rolfsimoes** [comment]
This is not an issue anymore
