### ISSUE TITLE
Support for Sentinel-1

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#249]
Include support for Sentinel-1 data in SITS. This support requires finding an effective solution for the fact that Sentinel-1 does not have a tile system, and thus requires either a major reprocessing or on-the-fly adjustments for interpolating each pixel.

**Comment by gilbertocamara** [comment]
Microsoft Planetary Computer has a Sentinel-1 image collection. Include support for collection asset and regularization.

**Comment by rolfsimoes** [comment]
- [ ] Add SENTINEL-1 in config.yml

**Comment by gilbertocamara** [comment]
We need to do a complete test of using Sentinel-1 for land classification before releasing full support for SAR images in SITS.
