### ISSUE TITLE
Band computation operations

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#251]
Include support for band computation operations in sits, following the design of similar operations in Google Earth Engine. The idea is that users can specify new functions, such as those required to define new indices. For examples, a use could specify a function to calculate the tasseled cap brightness index for Sentinel-2 as 
tcap <- function (B02, B03, B04, B08, B10, B12) {
        return 0.3037*B02 + 0.2793*B03 + 0.4743*B04 + 0.5585*B08 + 0.5082+B10 +0.1863*B12
}
then the function would be applied to a data cube 
cube_with_index <- sits_apply (s2_cube, tcap, "TCAP_B")

**Comment by pedro-andrade-inpe** [comment]
I think the code could be similar to `dplyr::mutate()`. Something like:

```R
cube_with_index <- s2_cube %>%
  sits_mutate(TCAP_B = 0.3037 * B02 + 0.2793 * B03 + 0.4743 * B04 + 0.5585 * B08 + 0.5082 * B10 + 0.1863 * B12)
```

**Comment by gilbertocamara** [comment]
For the implementation of band combination, I suggest we take a look at the chapter on "Metaprogramming" in the second edition of "Advanced R" by Hadley Wickham: https://adv-r.hadley.nz/metaprogramming.html
