### ISSUE TITLE
Semi-supervised learning

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#253]
Semisupervised learning techniques assumes that new training samples can be obtained from a (limited) set of available labeled samples without significant effort/cost

**Comment by albhasan** [comment]
Good morning. 

We prepared some slides on this subject some day ago, they are available [here](https://drive.google.com/file/d/1vZv8vquGE1nRH9PVLlpNY1PLzF8zCqqE/view?usp=sharing). 

My proposal is a function that takes 3 arguments, a sits tibble, a model specification, and a cube. The function trains the model using the given samples and then selects random points in the cube's extent. The function returns a sits tibble with the probabilities and the information entropy for both the training and the random samples. It is up to the user to filter the resulting tibble using the information entropy to select those samples which can be safely included in the next iteration of active learning and those which must go to the oracle, preferably an expert on remote sensing.

The signature of the function would be something like

`sits_active_learning(sits_tb, sits_model, data_cube)`

**Comment by gilbertocamara** [comment]
Hi Alber

Many thanks!
===========================
Prof Dr Gilberto Camara
Secretariat Director
GEO - Group on Earth Observations
https://gilbertocamara.org/
===============
Important: 
From 01.07.2021 the ***@***.*** address will no longer be valid. 
Please use ***@***.***

**Comment by gilbertocamara** [comment]
Superseded by #746
