### ISSUE TITLE
Problem - sits classify

### ISSUE THREAD

**Issue by TalitaTerra** [e-sensing/sits#255]
Hi,

I'm using sits (v0.11.0) with a local MODIS/TERRA cube, including NDVI, RED, NIR and MIR bands from 2015 to 2020. The images are large (8577 columns x 9988 lines), but I use the ROI parameter in the sits_classify function to subset the results. The images are stored in geographic/WGS-84 projection and the bounding box is xmin = -60.50200,  xmax = -41.24663, ymin= -24.70086, ymax= -2.27780. 

After creating the model based on random forest and running sits_classify with this ROI parameters (lat_min = -3.3, lat_max = -2.2, lon_min = -42.5, lon_max = -41.5), I get the following message: 

An error has occurred in a node and a recovery will be attempted at the end of the process
An error has occurred in a node and a recovery will be attempted at the end of the process 
Trying to recover failed nodes... 
Error: Some or all failed nodes could not be recovered 

The same error happens when omitting ROI parameter in sits_classify. 

Could you help me with this?

I'm looking forward to hearing from you.

Best regards,
TalitaTerra (GIZ/ TerraClass / Embrapa)

**Comment by rolfsimoes** [comment]
I believe the problem is due to differences in size between the cube and sample timelines.
Could you try `end_date = "2020-09-15"`?

It seems to me that the error is already a bug as it was supposed to throw an error right away and not try a recovery.
If the error still persists, can we schedule a call? In that case, just send me an email.

**Comment by TalitaTerra** [comment]
Hi Rolf,

Unfortunately, the error still persists. I've sent you an email.

Best regards,
Talita

**Comment by rolfsimoes** [comment]
I've tested the classification and the error message is:

Error in linear_interp(data) : All values are NA.

Ocean pixels has NoData value for MOD13Q1.

**Comment by gilbertocamara** [comment]
Talita, at the moment the sits package cannot deal with locations where all time instances are invalid. It expects to have at least one time instance with valid values.

**Comment by TalitaTerra** [comment]
Hi Gilberto and Rolf,
Thank you so much for the feedback. 
Because our area is a large one, it may have large bodies of water with null values, so we will see how to avoid them.
Thanks for all search.
Best regards,
Talita

**Comment by rolfsimoes** [comment]
Hi Talita,

This issue has been solved by simply converting full NA time series to zeroes.

This is by far not an ideal solution but currently `sits` is working with full NA time series.

We are still working on this at #266.

Thank you very much for your help!

Best regards
