### ISSUE TITLE
Produce uncertainty information from probability maps

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#256]
Overall accuracy estimates are not capable of indicating  the spatial variation of uncertainty in the image. 
To understand the problem, consider how wall-to-wall classification is done.  Experts first choose a set of samples for each class.  These samples train a classification model which is applied to every pixel in the image. Selection of training samples is subject to user bias.  Experts may have gone to the field and surveyed some areas but not others;  or they may miss differences in spectral response of a class in different areas of the image.  As a result, some areas in the image will be more accurately described than other.  From this reason, it is important to measure the spatial variability of the accuracy 
for the classification.

**Comment by rolfsimoes** [comment]
I suggest a new function called `sits_uncertainty()` to accommodate this functionality. Example:
```R
prob_cube <- sits_classify(...)
sits_uncertainty(probs_cube, method = "entropy")
```
