### ISSUE TITLE
Tuning function for sits models

### ISSUE THREAD

**Issue by OldLipe** [e-sensing/sits#262]
Function to choose the best parameters for the models implemented in the sits. Link [tune package](https://tune.tidymodels.org/index.html)

I thought of something like this:

```r
sits::sits_tuning(model, samples, parameter, steps)
```

Thanks!

**Comment by rolfsimoes** [comment]
I'm changing all non-priority issues to milestone version 0.12.1

**Comment by rolfsimoes** [comment]
@OldLipe, I think that the correct milestone for this feature is 0.13.0 as this will introduce incompatibility between sits version API.

**Comment by OldLipe** [comment]
@rolfsimoes, Ok. I will change it. Thanks!
