### ISSUE TITLE
Dealing with invalid areas in SITS

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#266]
Many image tiles cover ocean areas, where their values are set to NA. This is the case for Sentinel-2, Landsat, CBERS and MODIS. SITS needs to include a default land-sea mask to avoid wrong classification values.

**Comment by rolfsimoes** [comment]
Currently, `sits` is converting full NA time series to zero values which avoids an error.

This is not an ideal solution, but at least enables users to classify regions next to large water bodies, like oceans.

I think `sits` could automatically generates a mask indicating with how many valid values (i.e. no clouds, no shadows, no NA) each pixel was classified.
