### ISSUE TITLE
Error in using terra package of version 1.2-10 

### ISSUE THREAD

**Issue by OldLipe** [e-sensing/sits#281]
This error is related with this [issue](https://github.com/rspatial/terra/issues/250). Error occurs in sits when the smooth function is applied in an image with three classes.

This will be solved when the dev version going to CRAN.

**Comment by rolfsimoes** [comment]
To solve this issue, we need to require user to install terra at least 1.3.0 version.

**Comment by OldLipe** [comment]
The new version of the terra package is on [CRAN](https://cran.r-project.org/web/packages/terra/index.html). So I'm closing this issue.
