### ISSUE TITLE
Support for sits_config_sensor_bands accept more than one sensor

### ISSUE THREAD

**Issue by lorenalves** [e-sensing/sits#294]
The function  sits_config_sensor_bands() expect only one sensor. 
When the collection has more than one,  this error occurs: 
Error in sits_env$config[[sensor]] : no such index at level 2

**Comment by OldLipe** [comment]
Hello @rolfsimoes. Can i close this issue?

**Comment by OldLipe** [comment]
Closing this issue in [commit](https://github.com/rolfsimoes/sits/commit/780574812ad96b43d6cf8dc7ed09bfa123054ad2)
