### ISSUE TITLE
Error in cloud band of CBERS4 data example

### ISSUE THREAD

**Issue by rolfsimoes** [e-sensing/sits#378]
- Cloud band in `/inst/extdata/raster/cbers` example is wrong.
- When `sits` interpolates the time series, NA values are returned.
- Cloud raster files in the example has only 0.
- [Specification](https://brazil-data-cube.github.io/products/specifications/bands/CMASK.html) says that 0 means "No Data" and clear pixel has value 127.
- Cloud files in sits differ from their respective cloud files in BDC.

**Comment by gilbertocamara** [comment]
Solved by removing CBERS data from sits. This reduces the package size. Tests that used CBERS data have been replaced by MODIS data.
