### ISSUE TITLE
Add coord_quickmap() to plot

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#418]
ggplot2::coord_quickmap() helps plotting geographic information using ggplot2. It handles coordinate reference systems and more perhaps more important, it keeps the same scale along the X and Y axes.

**Comment by gilbertocamara** [comment]
Alber, thanks for the suggestion. Looking at the code, I could not find a suitable place to include coord_quickmap(). We are switching to leaflet for visualization, so I am not sure how could we benefit from your suggestion.
