### ISSUE TITLE
☁️ Count number of interpolated points in time series

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#424]
The function `sits_get_data` could return the number of clouded observations and the maximum number of consecutive clouded observations in each time series.

This would inform users about potential artifacts due to cloud interpolation (e.g. samples of two cycle agriculture appearing to have only one cycle).

**Comment by gilbertocamara** [comment]
`sits_get_data()` create a new column on a sits tibble, which informs if the time series value for each interval has been interpolated. This information is used for plotting and other functions.
