### ISSUE TITLE
documentation of sits_convnets

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#52]
Fix the documentation of `sits_convnets`:

```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'sits_convnets'
  ‘filters’ ‘kernels’
Documented arguments not in \usage in documentation object 'sits_convnets':
  ‘filter’ ‘kernel’
```

Please do not fix this issue yet. I'll use it to test the continuous integration service.

**Comment by gilbertocamara** [comment]
What version are you using? On the latest version, the check command is executed without any errors, warnings or notes.

**Comment by pedro-andrade-inpe** [comment]
My fault, I forgot to update my fork.
