### ISSUE TITLE
sits_services x sits_info_services

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#53]
What is the difference between `sits_services` and `sits_info_services`?

**Comment by gilbertocamara** [comment]
Pedro, the function sits_info_services is not exported. You may be referring to sits_infoWTSS, in which case, the package documentation says:
(a) sits_services - provides information about the time series services available
(b) sits_infoWTSS - provides information about WTSS service

We envisage that SITS will provide access to different time series data provision services. Curently there are two services available: SITS from INPE and SATVEG from EMBRAPA. We plan to add other services.

It may be the case that the names of the functions are not the most appropriate. Please help us in finding better names.

**Comment by pedro-andrade-inpe** [comment]
`sits_info_services` is not exported, but it is also not used by any other function of the package:

```bash
[pedro@~/github/sits/R] $ grep sits_info_services *
sits_info.R:#' @name sits_info_services
sits_info.R:sits_info_services <- function() {
[pedro@~/github/sits/R] $ 
```

Could it be removed?

**Comment by gilbertocamara** [comment]
Point taken. I will look into the matter and come back to you.

**Comment by gilbertocamara** [comment]
Included sits_info_services in the export list
