### ISSUE TITLE
NDVI time series with Spatio-temporal Savitzky-Golay

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#533]
The paper "_High-quality vegetation index product generation: A review of NDVI time series reconstruction techniques_" ([https://doi.org/10.1016/j.jag.2021.102640](url)) reviews methods for filling in the gaps in time series of satellite imagery. It compares temporal-based, frequency-based and hybrid methods and concludes that Spatio-temporal Savitzky-Golay (STSG) shows the best performance.

STSG would add value to the sits package.

**Comment by rolfsimoes** [comment]
Not necessary at the moment.
