### ISSUE TITLE
sits_get_data() Error: sits_get_data: invalid 'file' parameter (value is not character type)

### ISSUE THREAD

**Issue by kamaulindhardt** [e-sensing/sits#554]
**Dear Gilberto and collegues,** 

I am really excited about the sits package and I have been spending a little time to get to know it better. I am interested in using it to derive time series land use/cover phenology characteristics of an area around Nairobi, Kenya. 

For this, I have made an attemt to generate some training points in Google Earth Engine and exported them as a csv file. These training data contains the labels "Forest", "Agriculture", Urban" and "Water". 

- I have modified the training data points so they have similar format as the `/extdata/samples/samples_sinop_crop.csv` data. 

```
csv_training_points <- read_csv("lulc_training.csv") %>%
  select(-"...6") %>%
  rename(longitude = X,
         latitude = Y,
         label = landcover) %>%
  mutate(label = replace(label, label == 0, "Forest")) %>%
  mutate(label = replace(label, label == 1, "Urban")) %>%
  mutate(label = replace(label, label == 2, "Agriculture")) %>%
  mutate(label = replace(label, label == 3, "Water"))
```

csv_training_points

longitude<dbl> | latitude<dbl> | start_date<date> | end_date<date> | label<chr>
-- | -- | -- | -- | --
36.82774 | -1.237140 | 2018-07-01 | 2018-09-30 | Forest
36.84164 | -1.242117 | 2018-07-01 | 2018-09-30 | Forest
36.85194 | -1.248467 | 2018-07-01 | 2018-09-30 | Forest
36.80628 | -1.247352 | 2018-07-01 | 2018-09-30 | Forest
36.80386 | -1.274974 | 2018-07-01 | 2018-09-30 | Forest
36.76891 | -1.315544 | 2018-07-01 | 2018-09-30 | Forest
36.86796 | -1.155647 | 2018-07-01 | 2018-09-30 | Water
36.96620 | -1.175295 | 2018-07-01 | 2018-09-30 | Water
36.94355 | -1.187823 | 2018-07-01 | 2018-09-30 | Water
36.89874 | -1.174565 | 2018-07-01 | 2018-09-30 | Water
.. | .. | .. |.. |..

- Then, I have created a sits cube with the sits_cube() function for my area of interest: 

```
s3_cube <- sits_cube(
      source = "AWS",
      collection = "sentinel-s2-l2a-cogs",
      bands = c("B03", "B08", "B11", "CLOUD"),
      tiles = "37MBU",
      start_date = "2018-07-01",
      end_date = "2018-09-30"
)
```

- and reguralised it

```
s3_regular_cube <- sits_regularize(
      s3_cube,
      res = 60, 
      output_dir = ".",
      period = "P16D",
      agg_method = "median",
      cloud_mask = TRUE,
      multicores = 4
)
```

- and used it to retrieve the time series associated with the samples

 
`points <- sits_get_data(s3_regular_cube, file = csv_training_points)`

But then I run into an error I cannot understand(?)

`Error: sits_get_data: invalid 'file' parameter (value is not character type)`

What am I doing wrong here? 

Sorry if this is not the right place to post this kind of issue. Let me know.

_Grateful regards, 
Kamau_

**Comment by gilbertocamara** [comment]
Dear @kamaulindhardt, please write your samples as a csv file saved on disk. For exemple, the following should work:
```
utils::write.csv(csv_training_points, file = "./samples.csv", row.names = FALSE)
points <- sits_get_data(s3_regular_cube, file = "./samples.csv")
```
In the upcoming SITS version 0.16.1, we will include a new facility to read CSV files in memory. Sorry that this does not work yet.

**Comment by kamaulindhardt** [comment]
Thank you Gilberto, 

Using the samples as saved on disk memory works!
