### ISSUE TITLE
Raster Projection Problem

### ISSUE THREAD

**Issue by JieBNU** [e-sensing/sits#57]
Hi! Great package! 

I am trying the command sits_TWDTW_classify to map cropland by using Sentinel-2 tile. 

I found this package fail to identify the other projections, such as UTM. Because when I use the command sits_getdata to extract time series of points from tibble coverage, it always reports an error that "Error in spTransform(y, px) : error in pj_transform: latitude or longitude exceeded limits". 

I was wondering how to realize the functions, and whether there are any solutions when the projection of input data is UTM. 

Best regards

Jie

**Comment by gilbertocamara** [comment]
Hi Jie

Thanks for pointing out the problem. There is an issue with sits_TWDTW_classify with raster data. The main challenge is that the TWDTW algorithm is quite slow on raster files. We are working to fix this issues. Meanwhile, I suggest that you use the sits_classify_raster using one of the machine learning algorithms we provide in SITS. Our experience is that SVM, RandomForests and DeepLearning methods achieve a better performance than TWDTW, and are faster and easier to use.
