### ISSUE TITLE
Call sits_coverage failed

### ISSUE THREAD

**Issue by JieBNU** [e-sensing/sits#58]
Hello

I am getting an error when use the function sits_coverage. I use the command raster_cov <- sits_coverage(service = "RASTER", name = "Sinop-crop", timeline = timeline, bands = c("ndvi"), scale_factors = 1e-04, files = filename).

The error is "Error: conditions failed for call 'sits_coverage(service = "RASTER", name = "Sinop-crop", timeline = timeline, ': * !(purrr::is_null(.))
 Description: Not able to obtain scale factors for raster data"

However, I had set the scale_factors in the command before.
Some idea about how to solve this?

Best,
Jie

**Comment by gilbertocamara** [comment]
Dear Jie 

Thanks for the questions. The "scale_factors" and "files" parameters should be vector. Please try running the command as 
sits_coverage(service = "RASTER", name = "Sinop-crop", timeline = timeline, bands = c("ndvi"), scale_factors = c(1e-04), files = c(filename)).

I have just run the example provided in the "sits_raster_classification.R" function. See below:
% R
> library(sits)
> # Retrieve the set of samples for the Mato Grosso region (provided by EMBRAPA)
> data(samples_MT_ndvi)
> # read a raster file and put it into a vector
> files  <- c(system.file ("extdata/raster/mod13q1/sinop-crop-ndvi.tif", package = "sits"))
> # define the timeline
> data(timeline_modis_392)
> # create a raster metadata file based on the information about the files
> raster.tb <- sits_coverage(service = "RASTER", name  = "Sinop-crop",
               timeline = timeline_modis_392, bands = c("ndvi"), files = files)
> # classify the raster file
> raster_class.tb <- sits_classify_raster (file = "./raster-class", raster.tb, samples_MT_ndvi,
    ml_method = sits_svm(), blocksize = 250, multicores = 1)

**Comment by JieBNU** [comment]
Hi gilbertocamara

Sure, in my code, these two parameters (scale_factors and files) are indeed vector. But it still reports errors. 
However, when I use the other raster file, the command sits_coverage works. So I am wondering whether there is limitation for the raster file.
 
Best,
Jie
