### ISSUE TITLE
sits_conf_matrix error

### ISSUE THREAD

**Issue by albhasan** [e-sensing/sits#68]
sits_conf_matrix error fails when there are less than two classes in a predicted & reference tibble 

The code below throws the error:

 `data` and `reference` should be factors with the same levels. 

```
library(sits)
data(cerrado_2classes)
pred_ref.tb <-  sits_kfold_validate(cerrado_2classes, folds = 2)
conf.mx <- sits_conf_matrix(pred_ref.tb[1:10,])
```

R version

```
> R.Version()
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "4.4"

$year
[1] "2018"

$month
[1] "03"

$day
[1] "15"

$`svn rev`
[1] "74408"

$language
[1] "R"

$version.string
[1] "R version 3.4.4 (2018-03-15)"

$nickname
[1] "Someone to Lean On"
```

**Comment by albhasan** [comment]
The same error is produced even if there are more than two classes

```
library(sits)
data(cerrado_2classes)
pred_ref.tb <-  sits_kfold_validate(cerrado_2classes, folds = 2)
# > unique(pred_ref.tb$predicted)
# [1] "Cerrado" "Pasture"
# > unique(pred_ref.tb$reference)
# [1] "Cerrado" "Pasture"
conf.mx <- sits_conf_matrix(pred_ref.tb)
```

**Comment by gilbertocamara** [comment]
The code has been corrected to pass to caret::confusion_matrix the predicted and reference values as factors. However, when the user requests only a subset of the predicted/reference table, there can be more classes in the predicted part than in the reference part. This is a feature of the confusion matrix and cannot be corrected. Users advised not to subset the pred_ref table.
