### ISSUE TITLE
:ice_cube: cube classification with Savitsky-Golay filter is taking a long time

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#735]

**Comment by gilbertocamara** [comment]
See C++ implementation of Savitsky-Golay filter in https://github.com/robotsorcerer/Savitzky-Golay

**Comment by albhasan** [comment]
Computing Savitsky-Golay's coefficients uses Least Squares Estimates which require matrix inversion [0], which in turn,  is a costly operatrion (i.e. Gaussian elimination ~ O(n3)). However, Savitsky-Golay's coefficients don't depend on the data and can be pre-computed, stored, and reused efficiently. ` sits` could store these coefficients in an optimized table (similar to the one presented in [1]) . This table could be prunned to match the the time series' length available to `sits`.

[0] Savitzky-Golay Filter - Mathematical Details http://www.statistics4u.info/fundstat_eng/cc_filter_savgol_math.html#
[1] Savitzky-Golay Filter - Coefficients http://www.statistics4u.info/fundstat_eng/cc_savgol_coeff.html

**Comment by gilbertocamara** [comment]
Implemented in C++ and tested OK. Improvement of 3 times.
