### ISSUE TITLE
Problem with "sits_kfold_validate" when applying to deep learning models

### ISSUE THREAD

**Issue by joaowerner** [e-sensing/sits#749]
Hi,

I pasted the information from sessioninfo() in the print 1.
I'm trying to use the "sits_kfold_validate" function with ml_method=sits_tempcnn(), however I always get the error -> "Error in .check_remote_errors(cal): one node produced an error: Dimension out of range (expected to be in range of [-2,2], but got 3)"

The same error does not appear when I use another ml_method (sits_rfor for example). I think maybe it's not a problem with my tibble, since when I apply the "sits_train" function it runs perfectly. Do you know what this could be?

Thanks in advance.
João Paulo Werner.

![Sesion_info](https://user-images.githubusercontent.com/73180269/171255493-a456621a-88b5-4f65-ae57-e6991b71dd38.jpg)

![Cross_Validation](https://user-images.githubusercontent.com/73180269/171255519-01e29a5c-f237-43fa-b839-92c9e9acce5f.jpg)

![sits_train](https://user-images.githubusercontent.com/73180269/171255538-043342ba-dcf2-43cf-b672-1e07d7288e84.jpg)

**Comment by OldLipe** [comment]
Hi @joaowerner, 

I could not reproduce the reported error in my local environment. The reported error is related to the `torch` package. Please re-install the `torch` package.

Also, I used this code to try to reproduce your error:

```r
sits::sits_kfold_validate(
    samples = sits::samples_l8_rondonia_2bands,
    folds = 5,
    ml_method = sits::sits_tempcnn(),
    multicores = 2
)
```
Please see if running this code gives you the same error. 

If you have any questions, please feel free to contact me.

**Comment by joaowerner** [comment]
Hi @OldLipe,

I reinstalled the torch package, however for my dataset it doesn't work. I compared my data with "samples_l8_rondonia_2bands" and saw that the problem is when we have introduced data from several years (dimension out of range), considering the start and end date. For others "ml_method" running over multiple years works fine. So I think it could really be something related to some command on the torch that can be changed. Since I am working with three agricultural years, in building the model I need to consider all of them. Do you think it's possible to fix this? Thank you very much for your help, SITS has been very helpful to me.

**Comment by gilbertocamara** [comment]
Dear @joaowerner, could you please share your samples with us?

**Comment by joaowerner** [comment]
Dear @gilbertocamara, I sent the samples by email. Thanks.
