### ISSUE TITLE
Proposal to use the same framework to predict value

### ISSUE THREAD

**Issue by agronomofiorentini** [e-sensing/sits#802]
Dear creators,
First of all, congratulations on developing this framework, which I am using almost daily.

I would like to ask you if in the future you have thought of developing this package to be able to predict numerical values and not only for classification.

I am asking you this because right now I have yield data from a continuous weighted combine harvester and I would like to know if you could use the same framework to be able to train an algorithm to predict yield values from vegetation index data (e.g. NDVI and EVI)

Thanks for your time

**Comment by gilbertocamara** [comment]
Dear @agronomofiorentini, thanks for a nice suggestion. This is certainly an important addition to the "sits" package. In principle, "sits" could be extended to do prediction as well as classification. We would have to include new methods for training to include continuous Y variables and then change how prediction is done inside the "sits_classify" function. We will look carefully on how to achieve these goals and much time/effort it would take. We wil come back to you as soon as we have a clear position on what to do.

**Comment by OldLipe** [comment]
Move this issue to #1054.
