### ISSUE TITLE
'Rtools’ is not available' for R version 3.5.1

### ISSUE THREAD

**Issue by Gustavofba** [e-sensing/sits#82]
When I try to install sits (devtools::install_github("e-sensing/sits")) it shows 'Rtools’ package is not available' for R version 3.5.1. (it's the last one up 2018-08)

**Comment by pedro-andrade-inpe** [comment]
Just to register the solution. It is necessary to install Rtools manually because it is not an R package. Download and install it from:

https://cran.r-project.org/bin/windows/Rtools/

Then restart your R session and finally try to install sits again.
