### ISSUE TITLE
Create a README.Rmd

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#83]
The current README.md file uses R markdown, and not GitHub markdown. Create a README.Rmd in order to allow syntax highlight in the main page of sits package, in the same way of [dtwSat](https://github.com/vwmaus/dtwSat).

**Comment by gilbertocamara** [comment]
Created a new README.Rmd file which is an R markdown file. Running "knitr" on this file will create a "README.md" file which is compliant with the github markdown syntax.

**Comment by pedro-andrade-inpe** [comment]
This issue was solved by https://github.com/e-sensing/sits/commit/cbe9d4c0a18c6778cee4bfefcf436f6993aac0df
