### ISSUE TITLE
Random Forest Classification importance

### ISSUE THREAD

**Issue by ils15** [e-sensing/sits#830]
Hello. i'm trying to plot RF_importance and see RF calculated function in model
How can i see it?

**Comment by gilbertocamara** [comment]
You should install package "randomForestExplainer"

See MWE
```{r}
install.packages("randomForestExplainer")
library(sits)
library(randomForestExplainer)

# train a random forest model
rf_model <- sits_train(samples_modis_4bands,  ml_method = sits_rfor())
plot(rf_model)
```
Please let me know if it works for you.

**Comment by ils15** [comment]
Hi Gilberto
I saw randomForestExplainer with a lot of Random Forest Graphs. But plot only show minimal depth graphic. I cannot control random forest outputs, like importance, node purity, ranking, etc... and cannot see models details

**Comment by gilbertocamara** [comment]
We are currently analysing what is the benefit for general users to use the full power of randomForestExplainer. We have changed the sits "development" version to include additional parameters in `sits_rfor()` that would allow further model exploration by users. 
Please do as follows:
```{r}
# install the development version of sits
devtools::install_github("e-sensing/sits@dev")
# train a random forest model
rf_model <- sits_train(samples_modis_4bands,  ml_method = sits_rfor())
# extract the result of the R RandomForest package from the rf_model variable
rf_result <- environment(rf_model)$result_rfor
# use the rf_result variable with randomForestExplainer
randomForestExplainer::explain_forest(rf_result)
```
In future versions of SITS, we will consider including full support for RandomForestExplainer

**Comment by ils15** [comment]
Always good to have the model parameters and more control, especially for a more concise statistical analysis and a better evaluation in Random Forest modeling. It's valid to keep a greater amount of information, for greater control of what is generated, as well as the influence of variables in the modeling process. Even for cross-validation control in the SOM, for example.
@gilbertocamara Thank you for the answer. I will  test the new features of the dev version

**Comment by ils15** [comment]
Great. Thanks for fast answer.
