### ISSUE TITLE
⚠️Service BDC unreachable

### ISSUE THREAD

**Issue by Priscasantos** [e-sensing/sits#834]
Hi, good morning.
I'm having some problems acessing BDC throught sits. 
I'm using sits_cube() function and this is the reported problem:
**"Error: .source_collection_access_test.stac_cube: service is unreachable
 Failed to connect to brazildatacube.dpi.inpe.br port 443: Connection refused".**
I would like to know if BDC is offline.
Thank you.

**Comment by gqueiroz** [comment]
Please, try again. The services are all online now.

**Comment by Priscasantos** [comment]
It's normalized now. Thank u  so much @gqueiroz
