### ISSUE TITLE
Sits Service Unreachable

### ISSUE THREAD

**Issue by ils15** [e-sensing/sits#839]
Hello
Sits Service Unreacheable this morning

Error: .source_collection_access_test.stac_cube: service is unreachable
 Could not determine STAC version in URL 'https://brazildatacube.dpi.inpe.br/stac/'.
 
 Any routine maintain?

**Comment by OldLipe** [comment]
Hi @ils15. 

Yes, the service is under maintenance and will be back tomorrow.
