### ISSUE TITLE
Remove some sits dependencies

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#84]
Try to remove some dependencies of sits. Some candidates are:

(1) "mclust" - clustering functions of this package take to much time to process
(2) "signal" - implements Savitksy-Golay filter that could be implemented directly in sits 
(3) "tidyr" - only needed to run `fastApply` in the past but it is no longer used
(4) "openxlsx"- create an excel spreadsheet with the confusion matrix
(5) "pryr" - find out the free memory available.

**Comment by pedro-andrade-inpe** [comment]
I'll reopen this issue in order to try to remove more dependencies. Package itdepends might help:

```R
devtools::install_github("r-lib/vctrs")
devtools::install_github("r-lib/itdepends")

library(dplyr)
library(vctrs)
library(itdepends)

# PACKAGES

# Count dependencies
itdepends::dep_usage_pkg("sits") %>%
    count(pkg, sort = TRUE) %>% as.data.frame()
```

The number of calls to functions of each package sits uses is as follows:

```R
          pkg    n
1        base 7445
2        sits  577
3       dplyr  155
4       purrr  148
5    magrittr  138
6     ensurer  125
7       keras   88
8   lubridate   88
9     ggplot2   62
10     tibble   59
11      stats   44
12 data.table   36
13     raster   35
14    EOCubes   22
15         sf   21
16   graphics   15
17      utils   14
18       wtss   12
19   parallel   11
20      readr    8
21     dtwSat    7
22        zoo    7
23    kohonen    6
24   openxlsx    6
25      tools    6
26   dtwclust    4
27      log4r    4
28   reshape2    4
29      caret    3
30     config    3
31      RCurl    3
32    xgboost    3
33 dendextend    2
34  geosphere    2
35       MASS    2
36    methods    2
37       mgcv    2
38      rgdal    2
39     scales    2
40    stringr    2
41      e1071    1
42  flexclust    1
43  grDevices    1
44   imputeTS    1
45    NbClust    1
46       nnet    1
47      proxy    1
48     ranger    1
49     signal    1
50      tidyr    1
51   urltools    1
```

**Comment by gilbertocamara** [comment]
I will look at the dependencies and try to remove some of them.  It is going to be hard to clean. Some specific points:
26   dtwclust   :  required for cluster validity index
27      log4r : SITS log function (logging has proven quite useful in debugging)
28   reshape2 : essential for plotting, no alternative know
29      caret: essential for validity, well-know and useful packge
30     config: handles all configuration parameters (lots of work to remove it, no alternative known)
31      RCurl: will try to se if can merge with "urltools"
32    xgboost: essential for Extreme Gradient Boosting
33 dendextend: used to plot the dendrogram 
34  geosphere: not required (has been removed)
35       MASS: required for lda and qda (should we keep lda and qda?)
36    methods: tough one, used by plot dendrogram and dtwSat
37       mgcv: essential for computing patterns (no alternative known)
38      rgdal: essential 
39     scales: used to plot classification of time series (is there an alternative?)
40    stringr : replaced by grepl (package removed)
41      e1071: required for SVM
42  flexclust : required for sits_cluster_dendro_bestcut
43  grDevices: required for sits_plot and used to plot dendrogram
44   imputeTS : required for sits filtering (maybe can be removed - needs work here)
45    NbClust: not required, removed
46       nnet: required for multinomial log-linear model (remove this model?)
47      proxy: not called in any function (need to check sits_kohonen)
48     ranger: required by random forest model
49     signal: required by savitsky-golay filter (no replacement known)
50      tidyr: STRANGE: not called in SITS, not included in DESCRIPTION (why is it there?)
51   urltools: merge with RCurl???

**Comment by gilbertocamara** [comment]
Looked carefully in the code, and removed all dependencies which were not required. The rest is either required or hard to replace.
