### ISSUE TITLE
Github structure and new PR

### ISSUE THREAD

**Issue by ils15** [e-sensing/sits#840]
Hi
some advice about your github and structure

I don't usually follow many githubs, but since 2020 I've been working more closely with some repositories related to 3D printing (listed below).
In them, changes are listed in PR (and then committed when it accepted) and the issues part is dedicated to actual issues, bugs or New Features Requests. On your github, some of new features are implemented directly in the issues tab. 
I confess it causes me some strangeness and even difficulty in following up and suggesting improvements to the code. The problem is: there is a lot of things ''lost'' in issues, being necessary to look for the Commits manually (and look carefully line by line of modified code)
as a suggestion, i believe you can modify github structure to be something more global to understanding. This would make it easier for people to communicate, understand and contribute here within source code and project.

here some examples of github estrutures i talked about

https://github.com/MarlinFirmware/Marlin
https://github.com/prusa3d/PrusaSlicer
https://github.com/Ultimaker/Cura

**Comment by OldLipe** [comment]
Hi @ils15. 

Interesting. Indeed, a template for creating issues and PR can offer more flexibility to the community and contributors.
We will analyze it and get back to you. 

Thanks for the suggestion.

**Comment by gilbertocamara** [comment]
Dear @ils15, many thanks for your suggestions. It appears that we have different viewpoints about how "issues" should be used. Our view is that the "issues" area should allow those who are interested in the "sits" package to report bugs, but also to follow the development of the package. The idea is that external users can see the package roadmap and see what the developers are working on. Please note that in the R spatial community, such practice is commonplace. See for example https://github.com/r-spatial/sf.

**Comment by ils15** [comment]
What a think

implement a new feature, fix something bad, etc
Open a Pull Request

I really can't identify what was a bug, a fix, a new feature that is in progress or has already been implemented...
Sometimes it was implemented but i cannot identify when and how (need to search manually in commits)

For me ok, I adjusted myself here and I even managed to understand. But as the project progresses and more people participate, I believe it will become more difficult. I talk a lot with some people responsible for managing some githubs and most of them adopt this structure. As I said, I don't know if it's a pattern, but at least here it's the one that works best.

I imagine that a Feature Request or a New Feature could be done in issues

But the implementation roadmap should be done via PR (even if this PR is done by someone internal to the project), mentioning the new functionality open in Issue

For Example:

[New Feature] - Sits Cube Time Series map (issue)

[Pull Request] - Implemetantion of Sits Cube Time Series Map (PR opened to resolve issue)
As I said, it can be something of an adaptation, but I get lost sometimes trying to identify the roadmap, the PR and their links with the Issue

**Comment by gilbertocamara** [comment]
Hi @ils15

Experience on open source software and in particular, with R packages shows that, while the R ecosystem is highly collaborative, such support comes from small teams taking responsibilities for individual packages and ensuring they interoperate. The actual development of each package is done by a small team. For me, it is not clear why "pull requests" should be considered as a separate category. A PR is an action that is taken by a team member or collaborator to include/remove some lines of code. The PR can be a response to a user request, bug report, new development. Keeping PRs and issues separate has worked nicely for our team.

**Comment by ils15** [comment]
Ok
thanks
