### ISSUE TITLE
[FEAT] Crop classification result with `roi`

### ISSUE THREAD

**Issue by rolfsimoes** [e-sensing/sits#859]
**Describe the requested improvement**
If user pass a `roi` parameter, it can be used to crop final map.

**Associated sits API function**
This feature does not add any new parameter in `sits_classify()`.

**Additional context**
Cube with multiple tiles/crs requires roi reprojection.
This will improve result visualization of results to the user.

**Comment by gilbertocamara** [comment]
Solved by the `sits_mosaic()` function
