### ISSUE TITLE
Check if .sits_convert_resolution is necessary

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#89]
`.sits_convert_resolution()` does not work. Check if it is really necessary. The first two lines of this function are:

```R
    res <- vector()
    names[res] <- c("xres", "yres")
```
They should be as follows to work:

```R
    res <- vector(length = 2)
    names(res) <- c("xres", "yres")
```

This function is only called by `.sits_fromSHP()`, in an if that is never true in the tests:

```R
    if (coverage$xres > 1) {
        res <- .sits_convert_resolution(coverage)
        xres <- res["xres"]
        yres <- res["yres"]
    }
```

**Comment by gilbertocamara** [comment]
This test is required for coverages whose bounds are not expressed in EPSG 4326. For example, a raster image is a coverage not in EPSG 4326, so the coordinates have to be converted to lat/long. To test this function, one would need to write a test that retrieves data from a raster coverage inside a shapefile. This test requires a dummy shapefile to be created that works with the "sinop_crop_ndvi.tiff" file that is included in the inst/extdata directory.

**Comment by pedro-andrade-inpe** [comment]
Ok, the problem was because this function didn´t work. I´ll fix it.
