### ISSUE TITLE
Include a spatial segmentation function 

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#901]
Describe the new API function requested
Include a spatial segmentation function to support object-based classification (multi-band, single date)

Associated sits API function
sits_segmentation <- function (cube, bands, ref_date)
The output is a set of polygons convering the cube.

Additional context
The segmentation uses region-growing algorithm similar to the one used in SPRING. 

Bins, Leonardo Sant’Anna, Leila M Garcia Fonseca, Guaraci José Erthal, and Fernando Mitsuo Ii. 1996. ‘Satellite Imagery Segmentation: A Region Growing Approach’. In Brazilian Symposium on Remote Sensing. Salvador, Brazil.

**Comment by rolfsimoes** [comment]
Use `supercells` package.

**Comment by gilbertocamara** [comment]
supercells package works well.
