### ISSUE TITLE
Issue with downloading data before 2019

### ISSUE THREAD

**Issue by NvNorsinski** [e-sensing/sits#942]
Hello,
I have some issues with downloading data before the year 2019
```
file2 = "/mnt/eo/projekt/2023_STATeo_2_Austria/Fernerkundungsdaten/Sentinel2/2019"


s2_cube2 <- sits_cube(source = "AWS",
                     collection = "SENTINEL-S2-L2A-COGS",
                     tiles =  c("32TNS","32TPS", "32TNT","32TPT","32TQS", "32TQT","33UUP", "33TUM",
                                "33TUN","33TVM","33TVN","33TWM","33TWN","33TXN","33UVP","33UVQ","33UWP","33UXP","33UWQ","33UXQ"),
                     bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
                     start_date = as.Date("2019-03-01"),
                     end_date = as.Date("2019-10-30")
)




gc_cube2 <- sits_regularize(cube          = s2_cube2,
                           output_dir    = file2,
                           period        = "P15D",
                           res           = 10, 
                           multicores    = 8)


```

does work.

The exact same code but only the years changed
```

file = "2023_STATeo_2_Austria/Fernerkundungsdaten/Sentinel2/2017/"


s2_cube <- sits_cube(source = "AWS",
                     collection = "SENTINEL-S2-L2A-COGS",
                     tiles =  c("32TNS","32TPS", "32TNT","32TPT","32TQS", "32TQT","33UUP", "33TUM",
                                "33TUN","33TVM","33TVN","33TWM","33TWN","33TXN","33UVP","33UVQ","33UWP","33UXP","33UWQ","33UXQ"),
                     bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
                     start_date = as.Date("2017-03-01"),
                     end_date = as.Date("2017-10-30")
)




gc_cube <- sits_regularize(cube          = s2_cube,
                           output_dir    = file,
                           period        = "P15D",
                           res           = 10, 
                           multicores    = 14)



```
gives

`Error: .gc_get_valid_timeline: the timeline of the cube tiles do not intersect. (max_min_date <= min_max_date is not TRUE)`
what is obviously wrong.

And the same think for 2018 gives

```
s2_cube <- sits_cube(source = "AWS",
                     collection = "SENTINEL-S2-L2A-COGS",
                     tiles =  c("32TNS","32TPS", "32TNT","32TPT","32TQS", "32TQT","33UUP", "33TUM",
                                "33TUN","33TVM","33TVN","33TWM","33TWN","33TXN","33UVP","33UVQ","33UWP","33UXP","33UWQ","33UXQ"),
                     bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
                     start_date = as.Date("2018-03-01"),
                     end_date = as.Date("2018-10-30")
)

```

`Error: .source_items_cube.stac_cube: invalid feature id value (length should be 2143)`

For the years 2020 and 2021 it does all work. So I asume it must be some change in the Level2 data, but this is only speculation.

**Comment by OldLipe** [comment]
Hi @NvNorsinski ,

In my environment, I had no errors in the cube creation. Could you please provide the versions of the packages you're using?

However, I was able to reproduce the regularization error, which is related to the cube timeline.
> `.gc_get_valid_timeline: the timeline of the cube tiles do not intersect. (max_min_date <= min_max_date is not TRUE)`).

We have a restriction on regularization to ensure that all the tiles in the cube share the same timeline. In this 2017 cube, the minimum date that all tiles have an image starts from `2017-08-04`, but there are tiles in this cube that have only one date, e.g., tile `33UXQ` with an image of `2017-07-15`. 

The AWS open data collection has few images for some tiles from 2017, see the timeline for the same tile created with the Planetary Computer catalog.

```R
aws_cube <- sits_cube(
    source = "AWS",
    collection = "SENTINEL-S2-L2A-COGS",
    tiles = "33UXQ",
    bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
    start_date = "2017-03-01",
    end_date = "2017-10-30"
)
sits_timeline(aws_cube)
[1] "2017-07-15"

mpc_cube <- sits_cube(
    source = "MPC",
    collection = "SENTINEL-2-L2A",
    tiles = "33UXQ",
    bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
    start_date = "2017-03-01",
    end_date = "2017-10-30"
)
sits_timeline(mpc_cube)
 [1] "2017-03-02" "2017-03-09" "2017-03-12" "2017-03-19" "2017-03-22"
 [6] "2017-03-29" "2017-04-01" "2017-04-08" "2017-04-11" "2017-04-18"
[11] "2017-04-21" "2017-04-28" "2017-05-01" "2017-05-08" "2017-05-11"
[16] "2017-05-18" "2017-05-21" "2017-05-28" "2017-05-31" "2017-06-07"
[21] "2017-06-10" "2017-06-17" "2017-06-20" "2017-06-27" "2017-06-30"
[26] "2017-07-02" "2017-07-05" "2017-07-07" "2017-07-10" "2017-07-12"
[31] "2017-07-15" "2017-07-17" "2017-07-20" "2017-07-22" "2017-07-25"
[36] "2017-07-27" "2017-07-30" "2017-08-04" "2017-08-06" "2017-08-09"
[41] "2017-08-11" "2017-08-16" "2017-08-19" "2017-08-21" "2017-08-24"
[46] "2017-08-26" "2017-08-29" "2017-08-31" "2017-09-03" "2017-09-05"
[51] "2017-09-08" "2017-09-10" "2017-09-13" "2017-09-15" "2017-09-18"
[56] "2017-09-20" "2017-09-23" "2017-09-28" "2017-09-30" "2017-10-03"
[61] "2017-10-05" "2017-10-08" "2017-10-13" "2017-10-15" "2017-10-18"
[66] "2017-10-20" "2017-10-23" "2017-10-25" "2017-10-28"
```

The regularization error does not occur with Planetary Computer's cubes due to having more images:

```R
s2_cube <- sits_cube(
    source = "MPC",
    collection = "SENTINEL-2-L2A",
    tiles =  c("32TNS","32TPS", "32TNT","32TPT","32TQS", "32TQT","33UUP", "33TUM", "33TUN","33TVM","33TVN","33TWM","33TWN","33TXN","33UVP","33UVQ","33UWP","33UXP","33UWQ","33UXQ"),
    bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
    start_date = "2017-03-01",
    end_date = "2017-10-30"
)

file = "2023_STATeo_2_Austria/Fernerkundungsdaten/Sentinel2/2017/"

gc_cube <- sits_regularize(
    cube          = s2_cube,
    output_dir    = file,
    period        = "P15D",
    res           = 10, 
    multicores    = 14
)


```

**Comment by gilbertocamara** [comment]
Dear @NvNorsinski, as @OldLipe stated, the open access collection on AWS does not have all images from 2017. Please use those in Microsoft's Planetary Computer.

**Comment by NvNorsinski** [comment]
Thank you for your help so far. @OldLipe 
For the 2018 data I use R Version 4.2.1 and the Version of the SITS Package is 1.3.0. But i tried it also on older R and Package versions, resulting in the same error.

**Comment by felixg3** [comment]
> I tested it with MPC for one Tile and I got the message in the Screenshot. It does this over and over without stopping. I waited 4 hours to see what happens but there are no tiff files written in the directory. ![Unbenannt](https://user-images.githubusercontent.com/36541056/231165490-519ac622-577f-4e8e-80c9-c720c7494021.PNG)

I was experiencing the same issue on my local device, but currently, on sits@1.4 even with the MPC token I am rate limited (HTTP status '429'. Rate limit is exceeded. Try again in 60 seconds.)

I reached out to the MPC team and they couldn't immediately identify the issue. They assumed sits wouldn't use the mpc api to create tokens for each downloaded map.

**Comment by NvNorsinski** [comment]
@felixg3 Some where in the middle of the process I hade the same problem but I coult get arount It. I also uptated to version 1.4.
I createt a token from this MS page

https://planetarycomputer.microsoft.com/docs/reference/sas/
The code below works.

  ```
  library(sits)
 
  file = "2023_STATeo_2_Austria/Fernerkundungsdaten/Sentinel2/2018/"
  
  Sys.setenv("MPC_TOKEN" = "st=2023-04...... place your token here")
  
  
  s2_cube <- sits_cube(source = "MPC",
                       collection = "SENTINEL-2-L2A",
                       tiles =  c("32TNS","32TPS", "32TNT","32TPT","32TQS", "32TQT","33UUP", "33TUM",                            
                       "33TUN","33TVM","33TVN","33TWM","33TWN","33TXN","33UVP","33UVQ","33UWP","33UXP","33UWQ","33UXQ"),
                       bands = c("B02", "B03","B04","B05", "B06", "B07", "B08", "B8A", "B11", "B12", "CLOUD"),
                       start_date = as.Date("2018-03-01"),
                       end_date = as.Date("2018-10-30")
  )
  
  #cube_copy = sits_cube_copy(cube = s2_cube, res = 10, output_dir = file, progress = TRUE, multicores = 14)
  
  
  gc_cube <- sits_regularize(cube          = s2_cube,
                             output_dir    = file,
                             period        = "P15D",
                             res           = 10, 
                             multicores    = 14)
```

It will recomend you to use the cube_copy method but I hade some problems with that so I do not use it.

**Comment by gilbertocamara** [comment]
Dear @NvNorsinski @felixg3, using sits_cube_copy() is only appropriate when your data is close to the machine you are using. For example, accessing Microsoft Planetary Computer from an Azure VM, preferably in the same geography as MPC.

**Comment by NvNorsinski** [comment]
@felixg3 After some testing I saw it does indeed not download all the data. Some time stamps of some bands are missing. In the end it stopped with a progress of ~ 97 % and doing nothing then. It seems there are some problems with older data regarless of using AWS or MPC.
