### ISSUE TITLE
Include new function to clean NA values in classified  images

### ISSUE THREAD

**Issue by sadeckgeo** [e-sensing/sits#964]
**Describe the requested improvement**
When classifying Landsat images, especially older ones, there may be gaps and isolated pixels without data along the edges. Using GDAL to fill in these gaps can partially solve the problem, but it requires providing a minimum filling value. Therefore, it would be beneficial if the tool could fill in the missing data with the surrounding data instead of requiring a minimum value to be inputted.

**Comment by gilbertocamara** [comment]
Aim for version 1.4.2

**Comment by gilbertocamara** [comment]
Related to #994
