### ISSUE TITLE
Review sits_classify_raster memory and multicores

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#97]
`sits_classify_raster` uses 4GB of memory and the maximum number of cores minus one as default. Review these values, as the user might not have 4GB of memory available and might not want to use almost all processors. For example, `sits_classify` has `multicores = 1` as default.

**Comment by gilbertocamara** [comment]
The DESCRIPTION file has been amended to state that 4 GB and 2 cores are minimum requirements.
