### ISSUE TITLE
AWS collection SENTINEL-S2-L2A-COGS stopped updating

### ISSUE THREAD

**Issue by daniel-althoff** [e-sensing/sits#977]
**Describe the requested improvement**
I believe that the collection for SENTINEL-S2-L2A-COGS (https://earth-search.aws.element84.com/v0/search) stopped updating.
I think they have a new version running (https://earth-search.aws.element84.com/v1/search) although I am not sure it is available for SENTINEL-S2-L2A or is -COGS is also available.

**Associated sits API function**
```
bbox <- c(lon_min = -63.153456, 
          lat_min = -7.681265, 
          lon_max = -62.862239, 
          lat_max = -7.385608)

aws_s2 <- sits_cube(
  source = "AWS",
  collection = "SENTINEL-S2-L2A-COGS",
  roi = bbox,
  start_date = "2023-05-01",
  end_date = "2023-05-24"
)

sits_timeline(aws_s2)
```
returns only up until 2023-04-25

(I am using the 'oldLipe/sits@dev2' version that also has HLS, maybe that is it?)

**Comment by OldLipe** [comment]
Hi @daniel-althoff, thanks for the update. We are adding support for this new version of AWS STAC to the version 1.5 of sits.

**Comment by gilbertocamara** [comment]
Hi, @daniel-althoff, version 1.4.1 of sits, which will be submitted to CRAN tomorrow, contains a correction to this problem.
