### ISSUE TITLE
Review sits_patterns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [e-sensing/sits#98]
Review sits_patterns:

1. Argument `timeline` is useless
2. Arguments `start_date` and `end_date` are not month-day. They should be a Date, or a string that could be converted to a Date. The code below does not work:
```R
data(cerrado_2classes)
patterns.tb <- sits_patterns(cerrado_2classes, start_date ="09-13", end_date = "08-29")
```
3. If `start_date` is set as argument but not `end_date`, `start_date` will be overwritten, and vice-versa.
```R
        if (purrr::is_null(start_date) || purrr::is_null(end_date)) {
            start_date <- lubridate::as_date(utils::head(sample_dates, n = 1))
            end_date   <- lubridate::as_date(utils::tail(sample_dates, n = 1))
        }
```

**Comment by gilbertocamara** [comment]
Solved in version 0.08.06
