### ISSUE TITLE
[FEAT] Add modal function to classification cubes

### ISSUE THREAD

**Issue by OldLipe** [e-sensing/sits#990]
**Describe the requested improvement**
Add a function that applies the mode to classified cubes based on a window.

**Associated sits API function**
```
sits_clean(
    cube = cube, 
    clean_fn = sits_modal(),
    window_size = 3,
    memsize = 1,
    multicores = 2,
    output_dir
)
```

**Additional context**
Add any other context about the improvement here.

**Comment by gilbertocamara** [comment]
Aim for version 1.4.2
